/***************************************************************************
 *   Copyright (C) 2012~2012 by CSSlayer                                   *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.              *
 ***************************************************************************/

#include <fcitx-config/hotkey.h>
#include <QTextCodec>
#include <QDebug>
#include <ctype.h>
#include "qtkeytrans.h"
#include "qtkeytransdata.h"

#define _ARRAY_SIZE(a) (sizeof(a) / sizeof(a[0]))
#define _ARRAY_END(a) (a + _ARRAY_SIZE(a))

void qEventToSym(int key, const QString& text, Qt::KeyboardModifiers mod, int& outsym, unsigned int& outstate) {
    int sym = 0;
    int state = 0;
    do {
        if (text.length() <= 0)
            break;
        int uni = text[0].unicode();
        int* result = qBinaryFind(unicodeHasKey, _ARRAY_END(unicodeHasKey), uni);
        if (result != _ARRAY_END(unicodeHasKey)) {
            sym = *result + 0x1000000;
            break;
        }

        Unicode2Key* keyMap = qBinaryFind(unicodeKeyMap, _ARRAY_END(unicodeKeyMap), uni);
        if (keyMap != _ARRAY_END(unicodeKeyMap)) {
            sym = keyMap->key;
            break;
        }
    } while(0);

    do {
        if (sym)
            break;

        QtCode2Key* result = NULL;
        if (mod & Qt::KeypadModifier) {
            result = qBinaryFind(keyPadQtCodeToKey, _ARRAY_END(keyPadQtCodeToKey), key);
            if (result == _ARRAY_END(keyPadQtCodeToKey))
                result = NULL;
        }
        else {
            if (text.isNull()) {
                result = qBinaryFind(qtCodeToKeyBackup, _ARRAY_END(qtCodeToKeyBackup), key);
                if (result == _ARRAY_END(qtCodeToKeyBackup))
                    result = NULL;
            }
            else {
                result = qBinaryFind(qtCodeToKey, _ARRAY_END(qtCodeToKey), key);

                if (result == _ARRAY_END(qtCodeToKey))
                    result = NULL;
            }

            if (!result) {
                result = qBinaryFind(keyPadQtCodeToKey, _ARRAY_END(keyPadQtCodeToKey), key);
                if (result == _ARRAY_END(keyPadQtCodeToKey))
                    result = NULL;
            }
        }

        if (result)
            sym = result->key;

    } while (0);

    state = FcitxKeyState_None;

    if (mod & Qt::CTRL)
        state |= FcitxKeyState_Ctrl;

    if (mod & Qt::ALT)
        state |= FcitxKeyState_Alt;

    if (mod & Qt::SHIFT)
        state |= FcitxKeyState_Shift;

    if (mod & Qt::META)
        state |= FcitxKeyState_Super;

    outsym = sym;
    outstate= state;
}


FcitxKeySym syms[] = {
    FcitxKey_BackSpace,
    FcitxKey_Tab,
    FcitxKey_Linefeed,
    FcitxKey_Clear,
    FcitxKey_Return,
    FcitxKey_Pause,
    FcitxKey_Scroll_Lock,
    FcitxKey_Sys_Req,
    FcitxKey_Escape,
    FcitxKey_Delete,
    FcitxKey_Multi_key,
    FcitxKey_Codeinput,
    FcitxKey_SingleCandidate,
    FcitxKey_MultipleCandidate,
    FcitxKey_PreviousCandidate,
    FcitxKey_Kanji,
    FcitxKey_Muhenkan,
    FcitxKey_Henkan_Mode,
    FcitxKey_Henkan,
    FcitxKey_Romaji,
    FcitxKey_Hiragana,
    FcitxKey_Katakana,
    FcitxKey_Hiragana_Katakana,
    FcitxKey_Zenkaku,
    FcitxKey_Hankaku,
    FcitxKey_Zenkaku_Hankaku,
    FcitxKey_Touroku,
    FcitxKey_Massyo,
    FcitxKey_Kana_Lock,
    FcitxKey_Kana_Shift,
    FcitxKey_Eisu_Shift,
    FcitxKey_Eisu_toggle,
    FcitxKey_Kanji_Bangou,
    FcitxKey_Zen_Koho,
    FcitxKey_Mae_Koho,
    FcitxKey_Home,
    FcitxKey_Left,
    FcitxKey_Up,
    FcitxKey_Right,
    FcitxKey_Down,
    FcitxKey_Prior,
    FcitxKey_Page_Up,
    FcitxKey_Next,
    FcitxKey_Page_Down,
    FcitxKey_End,
    FcitxKey_Begin,
    FcitxKey_Select,
    FcitxKey_Print,
    FcitxKey_Execute,
    FcitxKey_Insert,
    FcitxKey_Undo,
    FcitxKey_Redo,
    FcitxKey_Menu,
    FcitxKey_Find,
    FcitxKey_Cancel,
    FcitxKey_Help,
    FcitxKey_Break,
    FcitxKey_Mode_switch,
    FcitxKey_script_switch,
    FcitxKey_Num_Lock,
    FcitxKey_KP_Space,
    FcitxKey_KP_Tab,
    FcitxKey_KP_Enter,
    FcitxKey_KP_F1,
    FcitxKey_KP_F2,
    FcitxKey_KP_F3,
    FcitxKey_KP_F4,
    FcitxKey_KP_Home,
    FcitxKey_KP_Left,
    FcitxKey_KP_Up,
    FcitxKey_KP_Right,
    FcitxKey_KP_Down,
    FcitxKey_KP_Prior,
    FcitxKey_KP_Page_Up,
    FcitxKey_KP_Next,
    FcitxKey_KP_Page_Down,
    FcitxKey_KP_End,
    FcitxKey_KP_Begin,
    FcitxKey_KP_Insert,
    FcitxKey_KP_Delete,
    FcitxKey_KP_Equal,
    FcitxKey_KP_Multiply,
    FcitxKey_KP_Add,
    FcitxKey_KP_Separator,
    FcitxKey_KP_Subtract,
    FcitxKey_KP_Decimal,
    FcitxKey_KP_Divide,
    FcitxKey_KP_0,
    FcitxKey_KP_1,
    FcitxKey_KP_2,
    FcitxKey_KP_3,
    FcitxKey_KP_4,
    FcitxKey_KP_5,
    FcitxKey_KP_6,
    FcitxKey_KP_7,
    FcitxKey_KP_8,
    FcitxKey_KP_9,
    FcitxKey_F1,
    FcitxKey_F2,
    FcitxKey_F3,
    FcitxKey_F4,
    FcitxKey_F5,
    FcitxKey_F6,
    FcitxKey_F7,
    FcitxKey_F8,
    FcitxKey_F9,
    FcitxKey_F10,
    FcitxKey_F11,
    FcitxKey_L1,
    FcitxKey_F12,
    FcitxKey_L2,
    FcitxKey_F13,
    FcitxKey_L3,
    FcitxKey_F14,
    FcitxKey_L4,
    FcitxKey_F15,
    FcitxKey_L5,
    FcitxKey_F16,
    FcitxKey_L6,
    FcitxKey_F17,
    FcitxKey_L7,
    FcitxKey_F18,
    FcitxKey_L8,
    FcitxKey_F19,
    FcitxKey_L9,
    FcitxKey_F20,
    FcitxKey_L10,
    FcitxKey_F21,
    FcitxKey_R1,
    FcitxKey_F22,
    FcitxKey_R2,
    FcitxKey_F23,
    FcitxKey_R3,
    FcitxKey_F24,
    FcitxKey_R4,
    FcitxKey_F25,
    FcitxKey_R5,
    FcitxKey_F26,
    FcitxKey_R6,
    FcitxKey_F27,
    FcitxKey_R7,
    FcitxKey_F28,
    FcitxKey_R8,
    FcitxKey_F29,
    FcitxKey_R9,
    FcitxKey_F30,
    FcitxKey_R10,
    FcitxKey_F31,
    FcitxKey_R11,
    FcitxKey_F32,
    FcitxKey_R12,
    FcitxKey_F33,
    FcitxKey_R13,
    FcitxKey_F34,
    FcitxKey_R14,
    FcitxKey_F35,
    FcitxKey_R15,
    FcitxKey_Shift_L,
    FcitxKey_Shift_R,
    FcitxKey_Control_L,
    FcitxKey_Control_R,
    FcitxKey_Caps_Lock,
    FcitxKey_Shift_Lock,
    FcitxKey_Meta_L,
    FcitxKey_Meta_R,
    FcitxKey_Alt_L,
    FcitxKey_Alt_R,
    FcitxKey_Super_L,
    FcitxKey_Super_R,
    FcitxKey_Hyper_L,
    FcitxKey_Hyper_R,
    FcitxKey_ISO_Lock,
    FcitxKey_ISO_Level2_Latch,
    FcitxKey_ISO_Level3_Shift,
    FcitxKey_ISO_Level3_Latch,
    FcitxKey_ISO_Level3_Lock,
    FcitxKey_ISO_Level5_Shift,
    FcitxKey_ISO_Level5_Latch,
    FcitxKey_ISO_Level5_Lock,
    FcitxKey_ISO_Group_Shift,
    FcitxKey_ISO_Group_Latch,
    FcitxKey_ISO_Group_Lock,
    FcitxKey_ISO_Next_Group,
    FcitxKey_ISO_Next_Group_Lock,
    FcitxKey_ISO_Prev_Group,
    FcitxKey_ISO_Prev_Group_Lock,
    FcitxKey_ISO_First_Group,
    FcitxKey_ISO_First_Group_Lock,
    FcitxKey_ISO_Last_Group,
    FcitxKey_ISO_Last_Group_Lock,
    FcitxKey_ISO_Left_Tab,
    FcitxKey_ISO_Move_Line_Up,
    FcitxKey_ISO_Move_Line_Down,
    FcitxKey_ISO_Partial_Line_Up,
    FcitxKey_ISO_Partial_Line_Down,
    FcitxKey_ISO_Partial_Space_Left,
    FcitxKey_ISO_Partial_Space_Right,
    FcitxKey_ISO_Set_Margin_Left,
    FcitxKey_ISO_Set_Margin_Right,
    FcitxKey_ISO_Release_Margin_Left,
    FcitxKey_ISO_Release_Margin_Right,
    FcitxKey_ISO_Release_Both_Margins,
    FcitxKey_ISO_Fast_Cursor_Left,
    FcitxKey_ISO_Fast_Cursor_Right,
    FcitxKey_ISO_Fast_Cursor_Up,
    FcitxKey_ISO_Fast_Cursor_Down,
    FcitxKey_ISO_Continuous_Underline,
    FcitxKey_ISO_Discontinuous_Underline,
    FcitxKey_ISO_Emphasize,
    FcitxKey_ISO_Center_Object,
    FcitxKey_ISO_Enter,
    FcitxKey_dead_grave,
    FcitxKey_dead_acute,
    FcitxKey_dead_circumflex,
    FcitxKey_dead_tilde,
    FcitxKey_dead_perispomeni,
    FcitxKey_dead_macron,
    FcitxKey_dead_breve,
    FcitxKey_dead_abovedot,
    FcitxKey_dead_diaeresis,
    FcitxKey_dead_abovering,
    FcitxKey_dead_doubleacute,
    FcitxKey_dead_caron,
    FcitxKey_dead_cedilla,
    FcitxKey_dead_ogonek,
    FcitxKey_dead_iota,
    FcitxKey_dead_voiced_sound,
    FcitxKey_dead_semivoiced_sound,
    FcitxKey_dead_belowdot,
    FcitxKey_dead_hook,
    FcitxKey_dead_horn,
    FcitxKey_dead_stroke,
    FcitxKey_dead_abovecomma,
    FcitxKey_dead_psili,
    FcitxKey_dead_abovereversedcomma,
    FcitxKey_dead_dasia,
    FcitxKey_dead_doublegrave,
    FcitxKey_dead_belowring,
    FcitxKey_dead_belowmacron,
    FcitxKey_dead_belowcircumflex,
    FcitxKey_dead_belowtilde,
    FcitxKey_dead_belowbreve,
    FcitxKey_dead_belowdiaeresis,
    FcitxKey_dead_invertedbreve,
    FcitxKey_dead_belowcomma,
    FcitxKey_dead_currency,
    FcitxKey_dead_a,
    FcitxKey_dead_A,
    FcitxKey_dead_e,
    FcitxKey_dead_E,
    FcitxKey_dead_i,
    FcitxKey_dead_I,
    FcitxKey_dead_o,
    FcitxKey_dead_O,
    FcitxKey_dead_u,
    FcitxKey_dead_U,
    FcitxKey_dead_small_schwa,
    FcitxKey_dead_capital_schwa,
    FcitxKey_First_Virtual_Screen,
    FcitxKey_Prev_Virtual_Screen,
    FcitxKey_Next_Virtual_Screen,
    FcitxKey_Last_Virtual_Screen,
    FcitxKey_Terminate_Server,
    FcitxKey_AccessX_Enable,
    FcitxKey_AccessX_Feedback_Enable,
    FcitxKey_RepeatKeys_Enable,
    FcitxKey_SlowKeys_Enable,
    FcitxKey_BounceKeys_Enable,
    FcitxKey_StickyKeys_Enable,
    FcitxKey_MouseKeys_Enable,
    FcitxKey_MouseKeys_Accel_Enable,
    FcitxKey_Overlay1_Enable,
    FcitxKey_Overlay2_Enable,
    FcitxKey_AudibleBell_Enable,
    FcitxKey_Pointer_Left,
    FcitxKey_Pointer_Right,
    FcitxKey_Pointer_Up,
    FcitxKey_Pointer_Down,
    FcitxKey_Pointer_UpLeft,
    FcitxKey_Pointer_UpRight,
    FcitxKey_Pointer_DownLeft,
    FcitxKey_Pointer_DownRight,
    FcitxKey_Pointer_Button_Dflt,
    FcitxKey_Pointer_Button1,
    FcitxKey_Pointer_Button2,
    FcitxKey_Pointer_Button3,
    FcitxKey_Pointer_Button4,
    FcitxKey_Pointer_Button5,
    FcitxKey_Pointer_DblClick_Dflt,
    FcitxKey_Pointer_DblClick1,
    FcitxKey_Pointer_DblClick2,
    FcitxKey_Pointer_DblClick3,
    FcitxKey_Pointer_DblClick4,
    FcitxKey_Pointer_DblClick5,
    FcitxKey_Pointer_Drag_Dflt,
    FcitxKey_Pointer_Drag1,
    FcitxKey_Pointer_Drag2,
    FcitxKey_Pointer_Drag3,
    FcitxKey_Pointer_Drag4,
    FcitxKey_Pointer_Drag5,
    FcitxKey_Pointer_EnableKeys,
    FcitxKey_Pointer_Accelerate,
    FcitxKey_Pointer_DfltBtnNext,
    FcitxKey_Pointer_DfltBtnPrev,
    FcitxKey_3270_Duplicate,
    FcitxKey_3270_FieldMark,
    FcitxKey_3270_Right2,
    FcitxKey_3270_Left2,
    FcitxKey_3270_BackTab,
    FcitxKey_3270_EraseEOF,
    FcitxKey_3270_EraseInput,
    FcitxKey_3270_Reset,
    FcitxKey_3270_Quit,
    FcitxKey_3270_PA1,
    FcitxKey_3270_PA2,
    FcitxKey_3270_PA3,
    FcitxKey_3270_Test,
    FcitxKey_3270_Attn,
    FcitxKey_3270_CursorBlink,
    FcitxKey_3270_AltCursor,
    FcitxKey_3270_KeyClick,
    FcitxKey_3270_Jump,
    FcitxKey_3270_Ident,
    FcitxKey_3270_Rule,
    FcitxKey_3270_Copy,
    FcitxKey_3270_Play,
    FcitxKey_3270_Setup,
    FcitxKey_3270_Record,
    FcitxKey_3270_ChangeScreen,
    FcitxKey_3270_DeleteWord,
    FcitxKey_3270_ExSelect,
    FcitxKey_3270_CursorSelect,
    FcitxKey_3270_PrintScreen,
    FcitxKey_3270_Enter,
    FcitxKey_space,
    FcitxKey_exclam,
    FcitxKey_quotedbl,
    FcitxKey_numbersign,
    FcitxKey_dollar,
    FcitxKey_percent,
    FcitxKey_ampersand,
    FcitxKey_apostrophe,
    FcitxKey_quoteright,
    FcitxKey_parenleft,
    FcitxKey_parenright,
    FcitxKey_asterisk,
    FcitxKey_plus,
    FcitxKey_comma,
    FcitxKey_minus,
    FcitxKey_period,
    FcitxKey_slash,
    FcitxKey_0,
    FcitxKey_1,
    FcitxKey_2,
    FcitxKey_3,
    FcitxKey_4,
    FcitxKey_5,
    FcitxKey_6,
    FcitxKey_7,
    FcitxKey_8,
    FcitxKey_9,
    FcitxKey_colon,
    FcitxKey_semicolon,
    FcitxKey_less,
    FcitxKey_equal,
    FcitxKey_greater,
    FcitxKey_question,
    FcitxKey_at,
    FcitxKey_A,
    FcitxKey_B,
    FcitxKey_C,
    FcitxKey_D,
    FcitxKey_E,
    FcitxKey_F,
    FcitxKey_G,
    FcitxKey_H,
    FcitxKey_I,
    FcitxKey_J,
    FcitxKey_K,
    FcitxKey_L,
    FcitxKey_M,
    FcitxKey_N,
    FcitxKey_O,
    FcitxKey_P,
    FcitxKey_Q,
    FcitxKey_R,
    FcitxKey_S,
    FcitxKey_T,
    FcitxKey_U,
    FcitxKey_V,
    FcitxKey_W,
    FcitxKey_X,
    FcitxKey_Y,
    FcitxKey_Z,
    FcitxKey_bracketleft,
    FcitxKey_backslash,
    FcitxKey_bracketright,
    FcitxKey_asciicircum,
    FcitxKey_underscore,
    FcitxKey_grave,
    FcitxKey_quoteleft,
    FcitxKey_a,
    FcitxKey_b,
    FcitxKey_c,
    FcitxKey_d,
    FcitxKey_e,
    FcitxKey_f,
    FcitxKey_g,
    FcitxKey_h,
    FcitxKey_i,
    FcitxKey_j,
    FcitxKey_k,
    FcitxKey_l,
    FcitxKey_m,
    FcitxKey_n,
    FcitxKey_o,
    FcitxKey_p,
    FcitxKey_q,
    FcitxKey_r,
    FcitxKey_s,
    FcitxKey_t,
    FcitxKey_u,
    FcitxKey_v,
    FcitxKey_w,
    FcitxKey_x,
    FcitxKey_y,
    FcitxKey_z,
    FcitxKey_braceleft,
    FcitxKey_bar,
    FcitxKey_braceright,
    FcitxKey_asciitilde,
    FcitxKey_nobreakspace,
    FcitxKey_exclamdown,
    FcitxKey_cent,
    FcitxKey_sterling,
    FcitxKey_currency,
    FcitxKey_yen,
    FcitxKey_brokenbar,
    FcitxKey_section,
    FcitxKey_diaeresis,
    FcitxKey_copyright,
    FcitxKey_ordfeminine,
    FcitxKey_guillemotleft,
    FcitxKey_notsign,
    FcitxKey_hyphen,
    FcitxKey_registered,
    FcitxKey_macron,
    FcitxKey_degree,
    FcitxKey_plusminus,
    FcitxKey_twosuperior,
    FcitxKey_threesuperior,
    FcitxKey_acute,
    FcitxKey_mu,
    FcitxKey_paragraph,
    FcitxKey_periodcentered,
    FcitxKey_cedilla,
    FcitxKey_onesuperior,
    FcitxKey_masculine,
    FcitxKey_guillemotright,
    FcitxKey_onequarter,
    FcitxKey_onehalf,
    FcitxKey_threequarters,
    FcitxKey_questiondown,
    FcitxKey_Agrave,
    FcitxKey_Aacute,
    FcitxKey_Acircumflex,
    FcitxKey_Atilde,
    FcitxKey_Adiaeresis,
    FcitxKey_Aring,
    FcitxKey_AE,
    FcitxKey_Ccedilla,
    FcitxKey_Egrave,
    FcitxKey_Eacute,
    FcitxKey_Ecircumflex,
    FcitxKey_Ediaeresis,
    FcitxKey_Igrave,
    FcitxKey_Iacute,
    FcitxKey_Icircumflex,
    FcitxKey_Idiaeresis,
    FcitxKey_ETH,
    FcitxKey_Eth,
    FcitxKey_Ntilde,
    FcitxKey_Ograve,
    FcitxKey_Oacute,
    FcitxKey_Ocircumflex,
    FcitxKey_Otilde,
    FcitxKey_Odiaeresis,
    FcitxKey_multiply,
    FcitxKey_Oslash,
    FcitxKey_Ooblique,
    FcitxKey_Ugrave,
    FcitxKey_Uacute,
    FcitxKey_Ucircumflex,
    FcitxKey_Udiaeresis,
    FcitxKey_Yacute,
    FcitxKey_THORN,
    FcitxKey_Thorn,
    FcitxKey_ssharp,
    FcitxKey_agrave,
    FcitxKey_aacute,
    FcitxKey_acircumflex,
    FcitxKey_atilde,
    FcitxKey_adiaeresis,
    FcitxKey_aring,
    FcitxKey_ae,
    FcitxKey_ccedilla,
    FcitxKey_egrave,
    FcitxKey_eacute,
    FcitxKey_ecircumflex,
    FcitxKey_ediaeresis,
    FcitxKey_igrave,
    FcitxKey_iacute,
    FcitxKey_icircumflex,
    FcitxKey_idiaeresis,
    FcitxKey_eth,
    FcitxKey_ntilde,
    FcitxKey_ograve,
    FcitxKey_oacute,
    FcitxKey_ocircumflex,
    FcitxKey_otilde,
    FcitxKey_odiaeresis,
    FcitxKey_division,
    FcitxKey_oslash,
    FcitxKey_ooblique,
    FcitxKey_ugrave,
    FcitxKey_uacute,
    FcitxKey_ucircumflex,
    FcitxKey_udiaeresis,
    FcitxKey_yacute,
    FcitxKey_thorn,
    FcitxKey_ydiaeresis,
    FcitxKey_Aogonek,
    FcitxKey_breve,
    FcitxKey_Lstroke,
    FcitxKey_Lcaron,
    FcitxKey_Sacute,
    FcitxKey_Scaron,
    FcitxKey_Scedilla,
    FcitxKey_Tcaron,
    FcitxKey_Zacute,
    FcitxKey_Zcaron,
    FcitxKey_Zabovedot,
    FcitxKey_aogonek,
    FcitxKey_ogonek,
    FcitxKey_lstroke,
    FcitxKey_lcaron,
    FcitxKey_sacute,
    FcitxKey_caron,
    FcitxKey_scaron,
    FcitxKey_scedilla,
    FcitxKey_tcaron,
    FcitxKey_zacute,
    FcitxKey_doubleacute,
    FcitxKey_zcaron,
    FcitxKey_zabovedot,
    FcitxKey_Racute,
    FcitxKey_Abreve,
    FcitxKey_Lacute,
    FcitxKey_Cacute,
    FcitxKey_Ccaron,
    FcitxKey_Eogonek,
    FcitxKey_Ecaron,
    FcitxKey_Dcaron,
    FcitxKey_Dstroke,
    FcitxKey_Nacute,
    FcitxKey_Ncaron,
    FcitxKey_Odoubleacute,
    FcitxKey_Rcaron,
    FcitxKey_Uring,
    FcitxKey_Udoubleacute,
    FcitxKey_Tcedilla,
    FcitxKey_racute,
    FcitxKey_abreve,
    FcitxKey_lacute,
    FcitxKey_cacute,
    FcitxKey_ccaron,
    FcitxKey_eogonek,
    FcitxKey_ecaron,
    FcitxKey_dcaron,
    FcitxKey_dstroke,
    FcitxKey_nacute,
    FcitxKey_ncaron,
    FcitxKey_odoubleacute,
    FcitxKey_udoubleacute,
    FcitxKey_rcaron,
    FcitxKey_uring,
    FcitxKey_tcedilla,
    FcitxKey_abovedot,
    FcitxKey_Hstroke,
    FcitxKey_Hcircumflex,
    FcitxKey_Iabovedot,
    FcitxKey_Gbreve,
    FcitxKey_Jcircumflex,
    FcitxKey_hstroke,
    FcitxKey_hcircumflex,
    FcitxKey_idotless,
    FcitxKey_gbreve,
    FcitxKey_jcircumflex,
    FcitxKey_Cabovedot,
    FcitxKey_Ccircumflex,
    FcitxKey_Gabovedot,
    FcitxKey_Gcircumflex,
    FcitxKey_Ubreve,
    FcitxKey_Scircumflex,
    FcitxKey_cabovedot,
    FcitxKey_ccircumflex,
    FcitxKey_gabovedot,
    FcitxKey_gcircumflex,
    FcitxKey_ubreve,
    FcitxKey_scircumflex,
    FcitxKey_kra,
    FcitxKey_kappa,
    FcitxKey_Rcedilla,
    FcitxKey_Itilde,
    FcitxKey_Lcedilla,
    FcitxKey_Emacron,
    FcitxKey_Gcedilla,
    FcitxKey_Tslash,
    FcitxKey_rcedilla,
    FcitxKey_itilde,
    FcitxKey_lcedilla,
    FcitxKey_emacron,
    FcitxKey_gcedilla,
    FcitxKey_tslash,
    FcitxKey_ENG,
    FcitxKey_eng,
    FcitxKey_Amacron,
    FcitxKey_Iogonek,
    FcitxKey_Eabovedot,
    FcitxKey_Imacron,
    FcitxKey_Ncedilla,
    FcitxKey_Omacron,
    FcitxKey_Kcedilla,
    FcitxKey_Uogonek,
    FcitxKey_Utilde,
    FcitxKey_Umacron,
    FcitxKey_amacron,
    FcitxKey_iogonek,
    FcitxKey_eabovedot,
    FcitxKey_imacron,
    FcitxKey_ncedilla,
    FcitxKey_omacron,
    FcitxKey_kcedilla,
    FcitxKey_uogonek,
    FcitxKey_utilde,
    FcitxKey_umacron,
    FcitxKey_Babovedot,
    FcitxKey_babovedot,
    FcitxKey_Dabovedot,
    FcitxKey_Wgrave,
    FcitxKey_Wacute,
    FcitxKey_dabovedot,
    FcitxKey_Ygrave,
    FcitxKey_Fabovedot,
    FcitxKey_fabovedot,
    FcitxKey_Mabovedot,
    FcitxKey_mabovedot,
    FcitxKey_Pabovedot,
    FcitxKey_wgrave,
    FcitxKey_pabovedot,
    FcitxKey_wacute,
    FcitxKey_Sabovedot,
    FcitxKey_ygrave,
    FcitxKey_Wdiaeresis,
    FcitxKey_wdiaeresis,
    FcitxKey_sabovedot,
    FcitxKey_Wcircumflex,
    FcitxKey_Tabovedot,
    FcitxKey_Ycircumflex,
    FcitxKey_wcircumflex,
    FcitxKey_tabovedot,
    FcitxKey_ycircumflex,
    FcitxKey_OE,
    FcitxKey_oe,
    FcitxKey_Ydiaeresis,
    FcitxKey_overline,
    FcitxKey_kana_fullstop,
    FcitxKey_kana_openingbracket,
    FcitxKey_kana_closingbracket,
    FcitxKey_kana_comma,
    FcitxKey_kana_conjunctive,
    FcitxKey_kana_middledot,
    FcitxKey_kana_WO,
    FcitxKey_kana_a,
    FcitxKey_kana_i,
    FcitxKey_kana_u,
    FcitxKey_kana_e,
    FcitxKey_kana_o,
    FcitxKey_kana_ya,
    FcitxKey_kana_yu,
    FcitxKey_kana_yo,
    FcitxKey_kana_tsu,
    FcitxKey_kana_tu,
    FcitxKey_prolongedsound,
    FcitxKey_kana_A,
    FcitxKey_kana_I,
    FcitxKey_kana_U,
    FcitxKey_kana_E,
    FcitxKey_kana_O,
    FcitxKey_kana_KA,
    FcitxKey_kana_KI,
    FcitxKey_kana_KU,
    FcitxKey_kana_KE,
    FcitxKey_kana_KO,
    FcitxKey_kana_SA,
    FcitxKey_kana_SHI,
    FcitxKey_kana_SU,
    FcitxKey_kana_SE,
    FcitxKey_kana_SO,
    FcitxKey_kana_TA,
    FcitxKey_kana_CHI,
    FcitxKey_kana_TI,
    FcitxKey_kana_TSU,
    FcitxKey_kana_TU,
    FcitxKey_kana_TE,
    FcitxKey_kana_TO,
    FcitxKey_kana_NA,
    FcitxKey_kana_NI,
    FcitxKey_kana_NU,
    FcitxKey_kana_NE,
    FcitxKey_kana_NO,
    FcitxKey_kana_HA,
    FcitxKey_kana_HI,
    FcitxKey_kana_FU,
    FcitxKey_kana_HU,
    FcitxKey_kana_HE,
    FcitxKey_kana_HO,
    FcitxKey_kana_MA,
    FcitxKey_kana_MI,
    FcitxKey_kana_MU,
    FcitxKey_kana_ME,
    FcitxKey_kana_MO,
    FcitxKey_kana_YA,
    FcitxKey_kana_YU,
    FcitxKey_kana_YO,
    FcitxKey_kana_RA,
    FcitxKey_kana_RI,
    FcitxKey_kana_RU,
    FcitxKey_kana_RE,
    FcitxKey_kana_RO,
    FcitxKey_kana_WA,
    FcitxKey_kana_N,
    FcitxKey_voicedsound,
    FcitxKey_semivoicedsound,
    FcitxKey_kana_switch,
    FcitxKey_Farsi_0,
    FcitxKey_Farsi_1,
    FcitxKey_Farsi_2,
    FcitxKey_Farsi_3,
    FcitxKey_Farsi_4,
    FcitxKey_Farsi_5,
    FcitxKey_Farsi_6,
    FcitxKey_Farsi_7,
    FcitxKey_Farsi_8,
    FcitxKey_Farsi_9,
    FcitxKey_Arabic_percent,
    FcitxKey_Arabic_superscript_alef,
    FcitxKey_Arabic_tteh,
    FcitxKey_Arabic_peh,
    FcitxKey_Arabic_tcheh,
    FcitxKey_Arabic_ddal,
    FcitxKey_Arabic_rreh,
    FcitxKey_Arabic_comma,
    FcitxKey_Arabic_fullstop,
    FcitxKey_Arabic_0,
    FcitxKey_Arabic_1,
    FcitxKey_Arabic_2,
    FcitxKey_Arabic_3,
    FcitxKey_Arabic_4,
    FcitxKey_Arabic_5,
    FcitxKey_Arabic_6,
    FcitxKey_Arabic_7,
    FcitxKey_Arabic_8,
    FcitxKey_Arabic_9,
    FcitxKey_Arabic_semicolon,
    FcitxKey_Arabic_question_mark,
    FcitxKey_Arabic_hamza,
    FcitxKey_Arabic_maddaonalef,
    FcitxKey_Arabic_hamzaonalef,
    FcitxKey_Arabic_hamzaonwaw,
    FcitxKey_Arabic_hamzaunderalef,
    FcitxKey_Arabic_hamzaonyeh,
    FcitxKey_Arabic_alef,
    FcitxKey_Arabic_beh,
    FcitxKey_Arabic_tehmarbuta,
    FcitxKey_Arabic_teh,
    FcitxKey_Arabic_theh,
    FcitxKey_Arabic_jeem,
    FcitxKey_Arabic_hah,
    FcitxKey_Arabic_khah,
    FcitxKey_Arabic_dal,
    FcitxKey_Arabic_thal,
    FcitxKey_Arabic_ra,
    FcitxKey_Arabic_zain,
    FcitxKey_Arabic_seen,
    FcitxKey_Arabic_sheen,
    FcitxKey_Arabic_sad,
    FcitxKey_Arabic_dad,
    FcitxKey_Arabic_tah,
    FcitxKey_Arabic_zah,
    FcitxKey_Arabic_ain,
    FcitxKey_Arabic_ghain,
    FcitxKey_Arabic_tatweel,
    FcitxKey_Arabic_feh,
    FcitxKey_Arabic_qaf,
    FcitxKey_Arabic_kaf,
    FcitxKey_Arabic_lam,
    FcitxKey_Arabic_meem,
    FcitxKey_Arabic_noon,
    FcitxKey_Arabic_ha,
    FcitxKey_Arabic_heh,
    FcitxKey_Arabic_waw,
    FcitxKey_Arabic_alefmaksura,
    FcitxKey_Arabic_yeh,
    FcitxKey_Arabic_fathatan,
    FcitxKey_Arabic_dammatan,
    FcitxKey_Arabic_kasratan,
    FcitxKey_Arabic_fatha,
    FcitxKey_Arabic_damma,
    FcitxKey_Arabic_kasra,
    FcitxKey_Arabic_shadda,
    FcitxKey_Arabic_sukun,
    FcitxKey_Arabic_madda_above,
    FcitxKey_Arabic_hamza_above,
    FcitxKey_Arabic_hamza_below,
    FcitxKey_Arabic_jeh,
    FcitxKey_Arabic_veh,
    FcitxKey_Arabic_keheh,
    FcitxKey_Arabic_gaf,
    FcitxKey_Arabic_noon_ghunna,
    FcitxKey_Arabic_heh_doachashmee,
    FcitxKey_Farsi_yeh,
    FcitxKey_Arabic_farsi_yeh,
    FcitxKey_Arabic_yeh_baree,
    FcitxKey_Arabic_heh_goal,
    FcitxKey_Arabic_switch,
    FcitxKey_Cyrillic_GHE_bar,
    FcitxKey_Cyrillic_ghe_bar,
    FcitxKey_Cyrillic_ZHE_descender,
    FcitxKey_Cyrillic_zhe_descender,
    FcitxKey_Cyrillic_KA_descender,
    FcitxKey_Cyrillic_ka_descender,
    FcitxKey_Cyrillic_KA_vertstroke,
    FcitxKey_Cyrillic_ka_vertstroke,
    FcitxKey_Cyrillic_EN_descender,
    FcitxKey_Cyrillic_en_descender,
    FcitxKey_Cyrillic_U_straight,
    FcitxKey_Cyrillic_u_straight,
    FcitxKey_Cyrillic_U_straight_bar,
    FcitxKey_Cyrillic_u_straight_bar,
    FcitxKey_Cyrillic_HA_descender,
    FcitxKey_Cyrillic_ha_descender,
    FcitxKey_Cyrillic_CHE_descender,
    FcitxKey_Cyrillic_che_descender,
    FcitxKey_Cyrillic_CHE_vertstroke,
    FcitxKey_Cyrillic_che_vertstroke,
    FcitxKey_Cyrillic_SHHA,
    FcitxKey_Cyrillic_shha,
    FcitxKey_Cyrillic_SCHWA,
    FcitxKey_Cyrillic_schwa,
    FcitxKey_Cyrillic_I_macron,
    FcitxKey_Cyrillic_i_macron,
    FcitxKey_Cyrillic_O_bar,
    FcitxKey_Cyrillic_o_bar,
    FcitxKey_Cyrillic_U_macron,
    FcitxKey_Cyrillic_u_macron,
    FcitxKey_Serbian_dje,
    FcitxKey_Macedonia_gje,
    FcitxKey_Cyrillic_io,
    FcitxKey_Ukrainian_ie,
    FcitxKey_Ukranian_je,
    FcitxKey_Macedonia_dse,
    FcitxKey_Ukrainian_i,
    FcitxKey_Ukranian_i,
    FcitxKey_Ukrainian_yi,
    FcitxKey_Ukranian_yi,
    FcitxKey_Cyrillic_je,
    FcitxKey_Serbian_je,
    FcitxKey_Cyrillic_lje,
    FcitxKey_Serbian_lje,
    FcitxKey_Cyrillic_nje,
    FcitxKey_Serbian_nje,
    FcitxKey_Serbian_tshe,
    FcitxKey_Macedonia_kje,
    FcitxKey_Ukrainian_ghe_with_upturn,
    FcitxKey_Byelorussian_shortu,
    FcitxKey_Cyrillic_dzhe,
    FcitxKey_Serbian_dze,
    FcitxKey_numerosign,
    FcitxKey_Serbian_DJE,
    FcitxKey_Macedonia_GJE,
    FcitxKey_Cyrillic_IO,
    FcitxKey_Ukrainian_IE,
    FcitxKey_Ukranian_JE,
    FcitxKey_Macedonia_DSE,
    FcitxKey_Ukrainian_I,
    FcitxKey_Ukranian_I,
    FcitxKey_Ukrainian_YI,
    FcitxKey_Ukranian_YI,
    FcitxKey_Cyrillic_JE,
    FcitxKey_Serbian_JE,
    FcitxKey_Cyrillic_LJE,
    FcitxKey_Serbian_LJE,
    FcitxKey_Cyrillic_NJE,
    FcitxKey_Serbian_NJE,
    FcitxKey_Serbian_TSHE,
    FcitxKey_Macedonia_KJE,
    FcitxKey_Ukrainian_GHE_WITH_UPTURN,
    FcitxKey_Byelorussian_SHORTU,
    FcitxKey_Cyrillic_DZHE,
    FcitxKey_Serbian_DZE,
    FcitxKey_Cyrillic_yu,
    FcitxKey_Cyrillic_a,
    FcitxKey_Cyrillic_be,
    FcitxKey_Cyrillic_tse,
    FcitxKey_Cyrillic_de,
    FcitxKey_Cyrillic_ie,
    FcitxKey_Cyrillic_ef,
    FcitxKey_Cyrillic_ghe,
    FcitxKey_Cyrillic_ha,
    FcitxKey_Cyrillic_i,
    FcitxKey_Cyrillic_shorti,
    FcitxKey_Cyrillic_ka,
    FcitxKey_Cyrillic_el,
    FcitxKey_Cyrillic_em,
    FcitxKey_Cyrillic_en,
    FcitxKey_Cyrillic_o,
    FcitxKey_Cyrillic_pe,
    FcitxKey_Cyrillic_ya,
    FcitxKey_Cyrillic_er,
    FcitxKey_Cyrillic_es,
    FcitxKey_Cyrillic_te,
    FcitxKey_Cyrillic_u,
    FcitxKey_Cyrillic_zhe,
    FcitxKey_Cyrillic_ve,
    FcitxKey_Cyrillic_softsign,
    FcitxKey_Cyrillic_yeru,
    FcitxKey_Cyrillic_ze,
    FcitxKey_Cyrillic_sha,
    FcitxKey_Cyrillic_e,
    FcitxKey_Cyrillic_shcha,
    FcitxKey_Cyrillic_che,
    FcitxKey_Cyrillic_hardsign,
    FcitxKey_Cyrillic_YU,
    FcitxKey_Cyrillic_A,
    FcitxKey_Cyrillic_BE,
    FcitxKey_Cyrillic_TSE,
    FcitxKey_Cyrillic_DE,
    FcitxKey_Cyrillic_IE,
    FcitxKey_Cyrillic_EF,
    FcitxKey_Cyrillic_GHE,
    FcitxKey_Cyrillic_HA,
    FcitxKey_Cyrillic_I,
    FcitxKey_Cyrillic_SHORTI,
    FcitxKey_Cyrillic_KA,
    FcitxKey_Cyrillic_EL,
    FcitxKey_Cyrillic_EM,
    FcitxKey_Cyrillic_EN,
    FcitxKey_Cyrillic_O,
    FcitxKey_Cyrillic_PE,
    FcitxKey_Cyrillic_YA,
    FcitxKey_Cyrillic_ER,
    FcitxKey_Cyrillic_ES,
    FcitxKey_Cyrillic_TE,
    FcitxKey_Cyrillic_U,
    FcitxKey_Cyrillic_ZHE,
    FcitxKey_Cyrillic_VE,
    FcitxKey_Cyrillic_SOFTSIGN,
    FcitxKey_Cyrillic_YERU,
    FcitxKey_Cyrillic_ZE,
    FcitxKey_Cyrillic_SHA,
    FcitxKey_Cyrillic_E,
    FcitxKey_Cyrillic_SHCHA,
    FcitxKey_Cyrillic_CHE,
    FcitxKey_Cyrillic_HARDSIGN,
    FcitxKey_Greek_ALPHAaccent,
    FcitxKey_Greek_EPSILONaccent,
    FcitxKey_Greek_ETAaccent,
    FcitxKey_Greek_IOTAaccent,
    FcitxKey_Greek_IOTAdieresis,
    FcitxKey_Greek_IOTAdiaeresis,
    FcitxKey_Greek_OMICRONaccent,
    FcitxKey_Greek_UPSILONaccent,
    FcitxKey_Greek_UPSILONdieresis,
    FcitxKey_Greek_OMEGAaccent,
    FcitxKey_Greek_accentdieresis,
    FcitxKey_Greek_horizbar,
    FcitxKey_Greek_alphaaccent,
    FcitxKey_Greek_epsilonaccent,
    FcitxKey_Greek_etaaccent,
    FcitxKey_Greek_iotaaccent,
    FcitxKey_Greek_iotadieresis,
    FcitxKey_Greek_iotaaccentdieresis,
    FcitxKey_Greek_omicronaccent,
    FcitxKey_Greek_upsilonaccent,
    FcitxKey_Greek_upsilondieresis,
    FcitxKey_Greek_upsilonaccentdieresis,
    FcitxKey_Greek_omegaaccent,
    FcitxKey_Greek_ALPHA,
    FcitxKey_Greek_BETA,
    FcitxKey_Greek_GAMMA,
    FcitxKey_Greek_DELTA,
    FcitxKey_Greek_EPSILON,
    FcitxKey_Greek_ZETA,
    FcitxKey_Greek_ETA,
    FcitxKey_Greek_THETA,
    FcitxKey_Greek_IOTA,
    FcitxKey_Greek_KAPPA,
    FcitxKey_Greek_LAMDA,
    FcitxKey_Greek_LAMBDA,
    FcitxKey_Greek_MU,
    FcitxKey_Greek_NU,
    FcitxKey_Greek_XI,
    FcitxKey_Greek_OMICRON,
    FcitxKey_Greek_PI,
    FcitxKey_Greek_RHO,
    FcitxKey_Greek_SIGMA,
    FcitxKey_Greek_TAU,
    FcitxKey_Greek_UPSILON,
    FcitxKey_Greek_PHI,
    FcitxKey_Greek_CHI,
    FcitxKey_Greek_PSI,
    FcitxKey_Greek_OMEGA,
    FcitxKey_Greek_alpha,
    FcitxKey_Greek_beta,
    FcitxKey_Greek_gamma,
    FcitxKey_Greek_delta,
    FcitxKey_Greek_epsilon,
    FcitxKey_Greek_zeta,
    FcitxKey_Greek_eta,
    FcitxKey_Greek_theta,
    FcitxKey_Greek_iota,
    FcitxKey_Greek_kappa,
    FcitxKey_Greek_lamda,
    FcitxKey_Greek_lambda,
    FcitxKey_Greek_mu,
    FcitxKey_Greek_nu,
    FcitxKey_Greek_xi,
    FcitxKey_Greek_omicron,
    FcitxKey_Greek_pi,
    FcitxKey_Greek_rho,
    FcitxKey_Greek_sigma,
    FcitxKey_Greek_finalsmallsigma,
    FcitxKey_Greek_tau,
    FcitxKey_Greek_upsilon,
    FcitxKey_Greek_phi,
    FcitxKey_Greek_chi,
    FcitxKey_Greek_psi,
    FcitxKey_Greek_omega,
    FcitxKey_Greek_switch,
    FcitxKey_leftradical,
    FcitxKey_topleftradical,
    FcitxKey_horizconnector,
    FcitxKey_topintegral,
    FcitxKey_botintegral,
    FcitxKey_vertconnector,
    FcitxKey_topleftsqbracket,
    FcitxKey_botleftsqbracket,
    FcitxKey_toprightsqbracket,
    FcitxKey_botrightsqbracket,
    FcitxKey_topleftparens,
    FcitxKey_botleftparens,
    FcitxKey_toprightparens,
    FcitxKey_botrightparens,
    FcitxKey_leftmiddlecurlybrace,
    FcitxKey_rightmiddlecurlybrace,
    FcitxKey_topleftsummation,
    FcitxKey_botleftsummation,
    FcitxKey_topvertsummationconnector,
    FcitxKey_botvertsummationconnector,
    FcitxKey_toprightsummation,
    FcitxKey_botrightsummation,
    FcitxKey_rightmiddlesummation,
    FcitxKey_lessthanequal,
    FcitxKey_notequal,
    FcitxKey_greaterthanequal,
    FcitxKey_integral,
    FcitxKey_therefore,
    FcitxKey_variation,
    FcitxKey_infinity,
    FcitxKey_nabla,
    FcitxKey_approximate,
    FcitxKey_similarequal,
    FcitxKey_ifonlyif,
    FcitxKey_implies,
    FcitxKey_identical,
//FcitxKey_radical,
    FcitxKey_includedin,
    FcitxKey_includes,
    FcitxKey_intersection,
    FcitxKey_union,
    FcitxKey_logicaland,
    FcitxKey_logicalor,
//FcitxKey_partialderivative,
    FcitxKey_function,
    FcitxKey_leftarrow,
    FcitxKey_uparrow,
    FcitxKey_rightarrow,
    FcitxKey_downarrow,
    FcitxKey_blank,
    FcitxKey_soliddiamond,
    FcitxKey_checkerboard,
    FcitxKey_ht,
    FcitxKey_ff,
    FcitxKey_cr,
    FcitxKey_lf,
    FcitxKey_nl,
    FcitxKey_vt,
    FcitxKey_lowrightcorner,
    FcitxKey_uprightcorner,
//FcitxKey_upleftcorner,
    FcitxKey_lowleftcorner,
    FcitxKey_crossinglines,
    FcitxKey_horizlinescan1,
    FcitxKey_horizlinescan3,
//FcitxKey_horizlinescan5,
    FcitxKey_horizlinescan7,
    FcitxKey_horizlinescan9,
    FcitxKey_leftt,
    FcitxKey_rightt,
    FcitxKey_bott,
    FcitxKey_topt,
//FcitxKey_vertbar,
    FcitxKey_emspace,
    FcitxKey_enspace,
    FcitxKey_em3space,
    FcitxKey_em4space,
    FcitxKey_digitspace,
    FcitxKey_punctspace,
    FcitxKey_thinspace,
    FcitxKey_hairspace,
    FcitxKey_emdash,
    FcitxKey_endash,
    FcitxKey_signifblank,
    FcitxKey_ellipsis,
    FcitxKey_doubbaselinedot,
    FcitxKey_onethird,
    FcitxKey_twothirds,
    FcitxKey_onefifth,
    FcitxKey_twofifths,
    FcitxKey_threefifths,
    FcitxKey_fourfifths,
    FcitxKey_onesixth,
    FcitxKey_fivesixths,
    FcitxKey_careof,
    FcitxKey_figdash,
    FcitxKey_leftanglebracket,
    FcitxKey_decimalpoint,
    FcitxKey_rightanglebracket,
    FcitxKey_marker,
    FcitxKey_oneeighth,
    FcitxKey_threeeighths,
    FcitxKey_fiveeighths,
    FcitxKey_seveneighths,
    FcitxKey_trademark,
    FcitxKey_signaturemark,
    FcitxKey_trademarkincircle,
    FcitxKey_leftopentriangle,
    FcitxKey_rightopentriangle,
    FcitxKey_emopencircle,
    FcitxKey_emopenrectangle,
    FcitxKey_leftsinglequotemark,
    FcitxKey_rightsinglequotemark,
    FcitxKey_leftdoublequotemark,
    FcitxKey_rightdoublequotemark,
    FcitxKey_prescription,
    FcitxKey_minutes,
    FcitxKey_seconds,
    FcitxKey_latincross,
    FcitxKey_hexagram,
    FcitxKey_filledrectbullet,
    FcitxKey_filledlefttribullet,
    FcitxKey_filledrighttribullet,
    FcitxKey_emfilledcircle,
    FcitxKey_emfilledrect,
    FcitxKey_enopencircbullet,
    FcitxKey_enopensquarebullet,
    FcitxKey_openrectbullet,
    FcitxKey_opentribulletup,
    FcitxKey_opentribulletdown,
    FcitxKey_openstar,
    FcitxKey_enfilledcircbullet,
    FcitxKey_enfilledsqbullet,
    FcitxKey_filledtribulletup,
    FcitxKey_filledtribulletdown,
    FcitxKey_leftpointer,
    FcitxKey_rightpointer,
    FcitxKey_club,
    FcitxKey_diamond,
    FcitxKey_heart,
    FcitxKey_maltesecross,
    FcitxKey_dagger,
    FcitxKey_doubledagger,
    FcitxKey_checkmark,
    FcitxKey_ballotcross,
    FcitxKey_musicalsharp,
    FcitxKey_musicalflat,
    FcitxKey_malesymbol,
    FcitxKey_femalesymbol,
    FcitxKey_telephone,
    FcitxKey_telephonerecorder,
    FcitxKey_phonographcopyright,
    FcitxKey_caret,
    FcitxKey_singlelowquotemark,
    FcitxKey_doublelowquotemark,
    FcitxKey_cursor,
//FcitxKey_leftcaret,
//FcitxKey_rightcaret,
//FcitxKey_downcaret,
//FcitxKey_upcaret,
//FcitxKey_overbar,
//FcitxKey_downtack,
//FcitxKey_upshoe,
    FcitxKey_downstile,
//FcitxKey_underbar,
    FcitxKey_jot,
    FcitxKey_quad,
    FcitxKey_uptack,
//FcitxKey_circle,
    FcitxKey_upstile,
//FcitxKey_downshoe,
//FcitxKey_rightshoe,
//FcitxKey_leftshoe,
    FcitxKey_lefttack,
    FcitxKey_righttack,
    FcitxKey_hebrew_doublelowline,
    FcitxKey_hebrew_aleph,
    FcitxKey_hebrew_bet,
    FcitxKey_hebrew_beth,
    FcitxKey_hebrew_gimel,
    FcitxKey_hebrew_gimmel,
    FcitxKey_hebrew_dalet,
    FcitxKey_hebrew_daleth,
    FcitxKey_hebrew_he,
    FcitxKey_hebrew_waw,
    FcitxKey_hebrew_zain,
    FcitxKey_hebrew_zayin,
    FcitxKey_hebrew_chet,
    FcitxKey_hebrew_het,
    FcitxKey_hebrew_tet,
    FcitxKey_hebrew_teth,
    FcitxKey_hebrew_yod,
    FcitxKey_hebrew_finalkaph,
    FcitxKey_hebrew_kaph,
    FcitxKey_hebrew_lamed,
    FcitxKey_hebrew_finalmem,
    FcitxKey_hebrew_mem,
    FcitxKey_hebrew_finalnun,
    FcitxKey_hebrew_nun,
    FcitxKey_hebrew_samech,
    FcitxKey_hebrew_samekh,
    FcitxKey_hebrew_ayin,
    FcitxKey_hebrew_finalpe,
    FcitxKey_hebrew_pe,
    FcitxKey_hebrew_finalzade,
    FcitxKey_hebrew_finalzadi,
    FcitxKey_hebrew_zade,
    FcitxKey_hebrew_zadi,
    FcitxKey_hebrew_qoph,
    FcitxKey_hebrew_kuf,
    FcitxKey_hebrew_resh,
    FcitxKey_hebrew_shin,
    FcitxKey_hebrew_taw,
    FcitxKey_hebrew_taf,
    FcitxKey_Hebrew_switch,
    FcitxKey_Thai_kokai,
    FcitxKey_Thai_khokhai,
    FcitxKey_Thai_khokhuat,
    FcitxKey_Thai_khokhwai,
    FcitxKey_Thai_khokhon,
    FcitxKey_Thai_khorakhang,
    FcitxKey_Thai_ngongu,
    FcitxKey_Thai_chochan,
    FcitxKey_Thai_choching,
    FcitxKey_Thai_chochang,
    FcitxKey_Thai_soso,
    FcitxKey_Thai_chochoe,
    FcitxKey_Thai_yoying,
    FcitxKey_Thai_dochada,
    FcitxKey_Thai_topatak,
    FcitxKey_Thai_thothan,
    FcitxKey_Thai_thonangmontho,
    FcitxKey_Thai_thophuthao,
    FcitxKey_Thai_nonen,
    FcitxKey_Thai_dodek,
    FcitxKey_Thai_totao,
    FcitxKey_Thai_thothung,
    FcitxKey_Thai_thothahan,
    FcitxKey_Thai_thothong,
    FcitxKey_Thai_nonu,
    FcitxKey_Thai_bobaimai,
    FcitxKey_Thai_popla,
    FcitxKey_Thai_phophung,
    FcitxKey_Thai_fofa,
    FcitxKey_Thai_phophan,
    FcitxKey_Thai_fofan,
    FcitxKey_Thai_phosamphao,
    FcitxKey_Thai_moma,
    FcitxKey_Thai_yoyak,
    FcitxKey_Thai_rorua,
    FcitxKey_Thai_ru,
    FcitxKey_Thai_loling,
    FcitxKey_Thai_lu,
    FcitxKey_Thai_wowaen,
    FcitxKey_Thai_sosala,
    FcitxKey_Thai_sorusi,
    FcitxKey_Thai_sosua,
    FcitxKey_Thai_hohip,
    FcitxKey_Thai_lochula,
    FcitxKey_Thai_oang,
    FcitxKey_Thai_honokhuk,
    FcitxKey_Thai_paiyannoi,
    FcitxKey_Thai_saraa,
    FcitxKey_Thai_maihanakat,
    FcitxKey_Thai_saraaa,
    FcitxKey_Thai_saraam,
    FcitxKey_Thai_sarai,
    FcitxKey_Thai_saraii,
    FcitxKey_Thai_saraue,
    FcitxKey_Thai_sarauee,
    FcitxKey_Thai_sarau,
    FcitxKey_Thai_sarauu,
    FcitxKey_Thai_phinthu,
    FcitxKey_Thai_maihanakat_maitho,
    FcitxKey_Thai_baht,
    FcitxKey_Thai_sarae,
    FcitxKey_Thai_saraae,
    FcitxKey_Thai_sarao,
    FcitxKey_Thai_saraaimaimuan,
    FcitxKey_Thai_saraaimaimalai,
    FcitxKey_Thai_lakkhangyao,
    FcitxKey_Thai_maiyamok,
    FcitxKey_Thai_maitaikhu,
    FcitxKey_Thai_maiek,
    FcitxKey_Thai_maitho,
    FcitxKey_Thai_maitri,
    FcitxKey_Thai_maichattawa,
    FcitxKey_Thai_thanthakhat,
    FcitxKey_Thai_nikhahit,
    FcitxKey_Thai_leksun,
    FcitxKey_Thai_leknung,
    FcitxKey_Thai_leksong,
    FcitxKey_Thai_leksam,
    FcitxKey_Thai_leksi,
    FcitxKey_Thai_lekha,
    FcitxKey_Thai_lekhok,
    FcitxKey_Thai_lekchet,
    FcitxKey_Thai_lekpaet,
    FcitxKey_Thai_lekkao,
    FcitxKey_Hangul,
    FcitxKey_Hangul_Start,
    FcitxKey_Hangul_End,
    FcitxKey_Hangul_Hanja,
    FcitxKey_Hangul_Jamo,
    FcitxKey_Hangul_Romaja,
    FcitxKey_Hangul_Codeinput,
    FcitxKey_Hangul_Jeonja,
    FcitxKey_Hangul_Banja,
    FcitxKey_Hangul_PreHanja,
    FcitxKey_Hangul_PostHanja,
    FcitxKey_Hangul_SingleCandidate,
    FcitxKey_Hangul_MultipleCandidate,
    FcitxKey_Hangul_PreviousCandidate,
    FcitxKey_Hangul_Special,
    FcitxKey_Hangul_switch,
    FcitxKey_Hangul_Kiyeog,
    FcitxKey_Hangul_SsangKiyeog,
    FcitxKey_Hangul_KiyeogSios,
    FcitxKey_Hangul_Nieun,
    FcitxKey_Hangul_NieunJieuj,
    FcitxKey_Hangul_NieunHieuh,
    FcitxKey_Hangul_Dikeud,
    FcitxKey_Hangul_SsangDikeud,
    FcitxKey_Hangul_Rieul,
    FcitxKey_Hangul_RieulKiyeog,
    FcitxKey_Hangul_RieulMieum,
    FcitxKey_Hangul_RieulPieub,
    FcitxKey_Hangul_RieulSios,
    FcitxKey_Hangul_RieulTieut,
    FcitxKey_Hangul_RieulPhieuf,
    FcitxKey_Hangul_RieulHieuh,
    FcitxKey_Hangul_Mieum,
    FcitxKey_Hangul_Pieub,
    FcitxKey_Hangul_SsangPieub,
    FcitxKey_Hangul_PieubSios,
    FcitxKey_Hangul_Sios,
    FcitxKey_Hangul_SsangSios,
    FcitxKey_Hangul_Ieung,
    FcitxKey_Hangul_Jieuj,
    FcitxKey_Hangul_SsangJieuj,
    FcitxKey_Hangul_Cieuc,
    FcitxKey_Hangul_Khieuq,
    FcitxKey_Hangul_Tieut,
    FcitxKey_Hangul_Phieuf,
    FcitxKey_Hangul_Hieuh,
    FcitxKey_Hangul_A,
    FcitxKey_Hangul_AE,
    FcitxKey_Hangul_YA,
    FcitxKey_Hangul_YAE,
    FcitxKey_Hangul_EO,
    FcitxKey_Hangul_E,
    FcitxKey_Hangul_YEO,
    FcitxKey_Hangul_YE,
    FcitxKey_Hangul_O,
    FcitxKey_Hangul_WA,
    FcitxKey_Hangul_WAE,
    FcitxKey_Hangul_OE,
    FcitxKey_Hangul_YO,
    FcitxKey_Hangul_U,
    FcitxKey_Hangul_WEO,
    FcitxKey_Hangul_WE,
    FcitxKey_Hangul_WI,
    FcitxKey_Hangul_YU,
    FcitxKey_Hangul_EU,
    FcitxKey_Hangul_YI,
    FcitxKey_Hangul_I,
    FcitxKey_Hangul_J_Kiyeog,
    FcitxKey_Hangul_J_SsangKiyeog,
    FcitxKey_Hangul_J_KiyeogSios,
    FcitxKey_Hangul_J_Nieun,
    FcitxKey_Hangul_J_NieunJieuj,
    FcitxKey_Hangul_J_NieunHieuh,
    FcitxKey_Hangul_J_Dikeud,
    FcitxKey_Hangul_J_Rieul,
    FcitxKey_Hangul_J_RieulKiyeog,
    FcitxKey_Hangul_J_RieulMieum,
    FcitxKey_Hangul_J_RieulPieub,
    FcitxKey_Hangul_J_RieulSios,
    FcitxKey_Hangul_J_RieulTieut,
    FcitxKey_Hangul_J_RieulPhieuf,
    FcitxKey_Hangul_J_RieulHieuh,
    FcitxKey_Hangul_J_Mieum,
    FcitxKey_Hangul_J_Pieub,
    FcitxKey_Hangul_J_PieubSios,
    FcitxKey_Hangul_J_Sios,
    FcitxKey_Hangul_J_SsangSios,
    FcitxKey_Hangul_J_Ieung,
    FcitxKey_Hangul_J_Jieuj,
    FcitxKey_Hangul_J_Cieuc,
    FcitxKey_Hangul_J_Khieuq,
    FcitxKey_Hangul_J_Tieut,
    FcitxKey_Hangul_J_Phieuf,
    FcitxKey_Hangul_J_Hieuh,
    FcitxKey_Hangul_RieulYeorinHieuh,
    FcitxKey_Hangul_SunkyeongeumMieum,
    FcitxKey_Hangul_SunkyeongeumPieub,
    FcitxKey_Hangul_PanSios,
    FcitxKey_Hangul_KkogjiDalrinIeung,
    FcitxKey_Hangul_SunkyeongeumPhieuf,
    FcitxKey_Hangul_YeorinHieuh,
    FcitxKey_Hangul_AraeA,
    FcitxKey_Hangul_AraeAE,
    FcitxKey_Hangul_J_PanSios,
    FcitxKey_Hangul_J_KkogjiDalrinIeung,
    FcitxKey_Hangul_J_YeorinHieuh,
//FcitxKey_Korean_Won,
    FcitxKey_Armenian_ligature_ew,
    FcitxKey_Armenian_full_stop,
    FcitxKey_Armenian_verjaket,
    FcitxKey_Armenian_separation_mark,
    FcitxKey_Armenian_but,
    FcitxKey_Armenian_hyphen,
    FcitxKey_Armenian_yentamna,
    FcitxKey_Armenian_exclam,
    FcitxKey_Armenian_amanak,
    FcitxKey_Armenian_accent,
    FcitxKey_Armenian_shesht,
    FcitxKey_Armenian_question,
    FcitxKey_Armenian_paruyk,
    FcitxKey_Armenian_AYB,
    FcitxKey_Armenian_ayb,
    FcitxKey_Armenian_BEN,
    FcitxKey_Armenian_ben,
    FcitxKey_Armenian_GIM,
    FcitxKey_Armenian_gim,
    FcitxKey_Armenian_DA,
    FcitxKey_Armenian_da,
    FcitxKey_Armenian_YECH,
    FcitxKey_Armenian_yech,
    FcitxKey_Armenian_ZA,
    FcitxKey_Armenian_za,
    FcitxKey_Armenian_E,
    FcitxKey_Armenian_e,
    FcitxKey_Armenian_AT,
    FcitxKey_Armenian_at,
    FcitxKey_Armenian_TO,
    FcitxKey_Armenian_to,
    FcitxKey_Armenian_ZHE,
    FcitxKey_Armenian_zhe,
    FcitxKey_Armenian_INI,
    FcitxKey_Armenian_ini,
    FcitxKey_Armenian_LYUN,
    FcitxKey_Armenian_lyun,
    FcitxKey_Armenian_KHE,
    FcitxKey_Armenian_khe,
    FcitxKey_Armenian_TSA,
    FcitxKey_Armenian_tsa,
    FcitxKey_Armenian_KEN,
    FcitxKey_Armenian_ken,
    FcitxKey_Armenian_HO,
    FcitxKey_Armenian_ho,
    FcitxKey_Armenian_DZA,
    FcitxKey_Armenian_dza,
    FcitxKey_Armenian_GHAT,
    FcitxKey_Armenian_ghat,
    FcitxKey_Armenian_TCHE,
    FcitxKey_Armenian_tche,
    FcitxKey_Armenian_MEN,
    FcitxKey_Armenian_men,
    FcitxKey_Armenian_HI,
    FcitxKey_Armenian_hi,
    FcitxKey_Armenian_NU,
    FcitxKey_Armenian_nu,
    FcitxKey_Armenian_SHA,
    FcitxKey_Armenian_sha,
    FcitxKey_Armenian_VO,
    FcitxKey_Armenian_vo,
    FcitxKey_Armenian_CHA,
    FcitxKey_Armenian_cha,
    FcitxKey_Armenian_PE,
    FcitxKey_Armenian_pe,
    FcitxKey_Armenian_JE,
    FcitxKey_Armenian_je,
    FcitxKey_Armenian_RA,
    FcitxKey_Armenian_ra,
    FcitxKey_Armenian_SE,
    FcitxKey_Armenian_se,
    FcitxKey_Armenian_VEV,
    FcitxKey_Armenian_vev,
    FcitxKey_Armenian_TYUN,
    FcitxKey_Armenian_tyun,
    FcitxKey_Armenian_RE,
    FcitxKey_Armenian_re,
    FcitxKey_Armenian_TSO,
    FcitxKey_Armenian_tso,
    FcitxKey_Armenian_VYUN,
    FcitxKey_Armenian_vyun,
    FcitxKey_Armenian_PYUR,
    FcitxKey_Armenian_pyur,
    FcitxKey_Armenian_KE,
    FcitxKey_Armenian_ke,
    FcitxKey_Armenian_O,
    FcitxKey_Armenian_o,
    FcitxKey_Armenian_FE,
    FcitxKey_Armenian_fe,
    FcitxKey_Armenian_apostrophe,
    FcitxKey_Georgian_an,
    FcitxKey_Georgian_ban,
    FcitxKey_Georgian_gan,
    FcitxKey_Georgian_don,
    FcitxKey_Georgian_en,
    FcitxKey_Georgian_vin,
    FcitxKey_Georgian_zen,
    FcitxKey_Georgian_tan,
    FcitxKey_Georgian_in,
    FcitxKey_Georgian_kan,
    FcitxKey_Georgian_las,
    FcitxKey_Georgian_man,
    FcitxKey_Georgian_nar,
    FcitxKey_Georgian_on,
    FcitxKey_Georgian_par,
    FcitxKey_Georgian_zhar,
    FcitxKey_Georgian_rae,
    FcitxKey_Georgian_san,
    FcitxKey_Georgian_tar,
    FcitxKey_Georgian_un,
    FcitxKey_Georgian_phar,
    FcitxKey_Georgian_khar,
    FcitxKey_Georgian_ghan,
    FcitxKey_Georgian_qar,
    FcitxKey_Georgian_shin,
    FcitxKey_Georgian_chin,
    FcitxKey_Georgian_can,
    FcitxKey_Georgian_jil,
    FcitxKey_Georgian_cil,
    FcitxKey_Georgian_char,
    FcitxKey_Georgian_xan,
    FcitxKey_Georgian_jhan,
    FcitxKey_Georgian_hae,
    FcitxKey_Georgian_he,
    FcitxKey_Georgian_hie,
    FcitxKey_Georgian_we,
    FcitxKey_Georgian_har,
    FcitxKey_Georgian_hoe,
    FcitxKey_Georgian_fi,
    FcitxKey_Xabovedot,
    FcitxKey_Ibreve,
    FcitxKey_Zstroke,
    FcitxKey_Gcaron,
    FcitxKey_Ocaron,
    FcitxKey_Obarred,
    FcitxKey_xabovedot,
    FcitxKey_ibreve,
    FcitxKey_zstroke,
    FcitxKey_gcaron,
    FcitxKey_ocaron,
    FcitxKey_obarred,
    FcitxKey_SCHWA,
    FcitxKey_schwa,
    FcitxKey_Lbelowdot,
    FcitxKey_lbelowdot,
    FcitxKey_Abelowdot,
    FcitxKey_abelowdot,
    FcitxKey_Ahook,
    FcitxKey_ahook,
    FcitxKey_Acircumflexacute,
    FcitxKey_acircumflexacute,
    FcitxKey_Acircumflexgrave,
    FcitxKey_acircumflexgrave,
    FcitxKey_Acircumflexhook,
    FcitxKey_acircumflexhook,
    FcitxKey_Acircumflextilde,
    FcitxKey_acircumflextilde,
    FcitxKey_Acircumflexbelowdot,
    FcitxKey_acircumflexbelowdot,
    FcitxKey_Abreveacute,
    FcitxKey_abreveacute,
    FcitxKey_Abrevegrave,
    FcitxKey_abrevegrave,
    FcitxKey_Abrevehook,
    FcitxKey_abrevehook,
    FcitxKey_Abrevetilde,
    FcitxKey_abrevetilde,
    FcitxKey_Abrevebelowdot,
    FcitxKey_abrevebelowdot,
    FcitxKey_Ebelowdot,
    FcitxKey_ebelowdot,
    FcitxKey_Ehook,
    FcitxKey_ehook,
    FcitxKey_Etilde,
    FcitxKey_etilde,
    FcitxKey_Ecircumflexacute,
    FcitxKey_ecircumflexacute,
    FcitxKey_Ecircumflexgrave,
    FcitxKey_ecircumflexgrave,
    FcitxKey_Ecircumflexhook,
    FcitxKey_ecircumflexhook,
    FcitxKey_Ecircumflextilde,
    FcitxKey_ecircumflextilde,
    FcitxKey_Ecircumflexbelowdot,
    FcitxKey_ecircumflexbelowdot,
    FcitxKey_Ihook,
    FcitxKey_ihook,
    FcitxKey_Ibelowdot,
    FcitxKey_ibelowdot,
    FcitxKey_Obelowdot,
    FcitxKey_obelowdot,
    FcitxKey_Ohook,
    FcitxKey_ohook,
    FcitxKey_Ocircumflexacute,
    FcitxKey_ocircumflexacute,
    FcitxKey_Ocircumflexgrave,
    FcitxKey_ocircumflexgrave,
    FcitxKey_Ocircumflexhook,
    FcitxKey_ocircumflexhook,
    FcitxKey_Ocircumflextilde,
    FcitxKey_ocircumflextilde,
    FcitxKey_Ocircumflexbelowdot,
    FcitxKey_ocircumflexbelowdot,
    FcitxKey_Ohornacute,
    FcitxKey_ohornacute,
    FcitxKey_Ohorngrave,
    FcitxKey_ohorngrave,
    FcitxKey_Ohornhook,
    FcitxKey_ohornhook,
    FcitxKey_Ohorntilde,
    FcitxKey_ohorntilde,
    FcitxKey_Ohornbelowdot,
    FcitxKey_ohornbelowdot,
    FcitxKey_Ubelowdot,
    FcitxKey_ubelowdot,
    FcitxKey_Uhook,
    FcitxKey_uhook,
    FcitxKey_Uhornacute,
    FcitxKey_uhornacute,
    FcitxKey_Uhorngrave,
    FcitxKey_uhorngrave,
    FcitxKey_Uhornhook,
    FcitxKey_uhornhook,
    FcitxKey_Uhorntilde,
    FcitxKey_uhorntilde,
    FcitxKey_Uhornbelowdot,
    FcitxKey_uhornbelowdot,
    FcitxKey_Ybelowdot,
    FcitxKey_ybelowdot,
    FcitxKey_Yhook,
    FcitxKey_yhook,
    FcitxKey_Ytilde,
    FcitxKey_ytilde,
    FcitxKey_Ohorn,
    FcitxKey_ohorn,
    FcitxKey_Uhorn,
    FcitxKey_uhorn,
    FcitxKey_EcuSign,
    FcitxKey_ColonSign,
    FcitxKey_CruzeiroSign,
    FcitxKey_FFrancSign,
    FcitxKey_LiraSign,
    FcitxKey_MillSign,
    FcitxKey_NairaSign,
    FcitxKey_PesetaSign,
    FcitxKey_RupeeSign,
    FcitxKey_WonSign,
    FcitxKey_NewSheqelSign,
    FcitxKey_DongSign,
    FcitxKey_EuroSign,
    FcitxKey_zerosuperior,
    FcitxKey_foursuperior,
    FcitxKey_fivesuperior,
    FcitxKey_sixsuperior,
    FcitxKey_sevensuperior,
    FcitxKey_eightsuperior,
    FcitxKey_ninesuperior,
    FcitxKey_zerosubscript,
    FcitxKey_onesubscript,
    FcitxKey_twosubscript,
    FcitxKey_threesubscript,
    FcitxKey_foursubscript,
    FcitxKey_fivesubscript,
    FcitxKey_sixsubscript,
    FcitxKey_sevensubscript,
    FcitxKey_eightsubscript,
    FcitxKey_ninesubscript,
    FcitxKey_partdifferential,
    FcitxKey_emptyset,
    FcitxKey_elementof,
    FcitxKey_notelementof,
    FcitxKey_containsas,
    FcitxKey_squareroot,
    FcitxKey_cuberoot,
    FcitxKey_fourthroot,
    FcitxKey_dintegral,
    FcitxKey_tintegral,
    FcitxKey_because,
    FcitxKey_approxeq,
    FcitxKey_notapproxeq,
    FcitxKey_notidentical,
    FcitxKey_stricteq,
    FcitxKey_braille_dot_1,
    FcitxKey_braille_dot_2,
    FcitxKey_braille_dot_3,
    FcitxKey_braille_dot_4,
    FcitxKey_braille_dot_5,
    FcitxKey_braille_dot_6,
    FcitxKey_braille_dot_7,
    FcitxKey_braille_dot_8,
    FcitxKey_braille_dot_9,
    FcitxKey_braille_dot_10,
    FcitxKey_braille_blank,
    FcitxKey_braille_dots_1,
    FcitxKey_braille_dots_2,
    FcitxKey_braille_dots_12,
    FcitxKey_braille_dots_3,
    FcitxKey_braille_dots_13,
    FcitxKey_braille_dots_23,
    FcitxKey_braille_dots_123,
    FcitxKey_braille_dots_4,
    FcitxKey_braille_dots_14,
    FcitxKey_braille_dots_24,
    FcitxKey_braille_dots_124,
    FcitxKey_braille_dots_34,
    FcitxKey_braille_dots_134,
    FcitxKey_braille_dots_234,
    FcitxKey_braille_dots_1234,
    FcitxKey_braille_dots_5,
    FcitxKey_braille_dots_15,
    FcitxKey_braille_dots_25,
    FcitxKey_braille_dots_125,
    FcitxKey_braille_dots_35,
    FcitxKey_braille_dots_135,
    FcitxKey_braille_dots_235,
    FcitxKey_braille_dots_1235,
    FcitxKey_braille_dots_45,
    FcitxKey_braille_dots_145,
    FcitxKey_braille_dots_245,
    FcitxKey_braille_dots_1245,
    FcitxKey_braille_dots_345,
    FcitxKey_braille_dots_1345,
    FcitxKey_braille_dots_2345,
    FcitxKey_braille_dots_12345,
    FcitxKey_braille_dots_6,
    FcitxKey_braille_dots_16,
    FcitxKey_braille_dots_26,
    FcitxKey_braille_dots_126,
    FcitxKey_braille_dots_36,
    FcitxKey_braille_dots_136,
    FcitxKey_braille_dots_236,
    FcitxKey_braille_dots_1236,
    FcitxKey_braille_dots_46,
    FcitxKey_braille_dots_146,
    FcitxKey_braille_dots_246,
    FcitxKey_braille_dots_1246,
    FcitxKey_braille_dots_346,
    FcitxKey_braille_dots_1346,
    FcitxKey_braille_dots_2346,
    FcitxKey_braille_dots_12346,
    FcitxKey_braille_dots_56,
    FcitxKey_braille_dots_156,
    FcitxKey_braille_dots_256,
    FcitxKey_braille_dots_1256,
    FcitxKey_braille_dots_356,
    FcitxKey_braille_dots_1356,
    FcitxKey_braille_dots_2356,
    FcitxKey_braille_dots_12356,
    FcitxKey_braille_dots_456,
    FcitxKey_braille_dots_1456,
    FcitxKey_braille_dots_2456,
    FcitxKey_braille_dots_12456,
    FcitxKey_braille_dots_3456,
    FcitxKey_braille_dots_13456,
    FcitxKey_braille_dots_23456,
    FcitxKey_braille_dots_123456,
    FcitxKey_braille_dots_7,
    FcitxKey_braille_dots_17,
    FcitxKey_braille_dots_27,
    FcitxKey_braille_dots_127,
    FcitxKey_braille_dots_37,
    FcitxKey_braille_dots_137,
    FcitxKey_braille_dots_237,
    FcitxKey_braille_dots_1237,
    FcitxKey_braille_dots_47,
    FcitxKey_braille_dots_147,
    FcitxKey_braille_dots_247,
    FcitxKey_braille_dots_1247,
    FcitxKey_braille_dots_347,
    FcitxKey_braille_dots_1347,
    FcitxKey_braille_dots_2347,
    FcitxKey_braille_dots_12347,
    FcitxKey_braille_dots_57,
    FcitxKey_braille_dots_157,
    FcitxKey_braille_dots_257,
    FcitxKey_braille_dots_1257,
    FcitxKey_braille_dots_357,
    FcitxKey_braille_dots_1357,
    FcitxKey_braille_dots_2357,
    FcitxKey_braille_dots_12357,
    FcitxKey_braille_dots_457,
    FcitxKey_braille_dots_1457,
    FcitxKey_braille_dots_2457,
    FcitxKey_braille_dots_12457,
    FcitxKey_braille_dots_3457,
    FcitxKey_braille_dots_13457,
    FcitxKey_braille_dots_23457,
    FcitxKey_braille_dots_123457,
    FcitxKey_braille_dots_67,
    FcitxKey_braille_dots_167,
    FcitxKey_braille_dots_267,
    FcitxKey_braille_dots_1267,
    FcitxKey_braille_dots_367,
    FcitxKey_braille_dots_1367,
    FcitxKey_braille_dots_2367,
    FcitxKey_braille_dots_12367,
    FcitxKey_braille_dots_467,
    FcitxKey_braille_dots_1467,
    FcitxKey_braille_dots_2467,
    FcitxKey_braille_dots_12467,
    FcitxKey_braille_dots_3467,
    FcitxKey_braille_dots_13467,
    FcitxKey_braille_dots_23467,
    FcitxKey_braille_dots_123467,
    FcitxKey_braille_dots_567,
    FcitxKey_braille_dots_1567,
    FcitxKey_braille_dots_2567,
    FcitxKey_braille_dots_12567,
    FcitxKey_braille_dots_3567,
    FcitxKey_braille_dots_13567,
    FcitxKey_braille_dots_23567,
    FcitxKey_braille_dots_123567,
    FcitxKey_braille_dots_4567,
    FcitxKey_braille_dots_14567,
    FcitxKey_braille_dots_24567,
    FcitxKey_braille_dots_124567,
    FcitxKey_braille_dots_34567,
    FcitxKey_braille_dots_134567,
    FcitxKey_braille_dots_234567,
    FcitxKey_braille_dots_1234567,
    FcitxKey_braille_dots_8,
    FcitxKey_braille_dots_18,
    FcitxKey_braille_dots_28,
    FcitxKey_braille_dots_128,
    FcitxKey_braille_dots_38,
    FcitxKey_braille_dots_138,
    FcitxKey_braille_dots_238,
    FcitxKey_braille_dots_1238,
    FcitxKey_braille_dots_48,
    FcitxKey_braille_dots_148,
    FcitxKey_braille_dots_248,
    FcitxKey_braille_dots_1248,
    FcitxKey_braille_dots_348,
    FcitxKey_braille_dots_1348,
    FcitxKey_braille_dots_2348,
    FcitxKey_braille_dots_12348,
    FcitxKey_braille_dots_58,
    FcitxKey_braille_dots_158,
    FcitxKey_braille_dots_258,
    FcitxKey_braille_dots_1258,
    FcitxKey_braille_dots_358,
    FcitxKey_braille_dots_1358,
    FcitxKey_braille_dots_2358,
    FcitxKey_braille_dots_12358,
    FcitxKey_braille_dots_458,
    FcitxKey_braille_dots_1458,
    FcitxKey_braille_dots_2458,
    FcitxKey_braille_dots_12458,
    FcitxKey_braille_dots_3458,
    FcitxKey_braille_dots_13458,
    FcitxKey_braille_dots_23458,
    FcitxKey_braille_dots_123458,
    FcitxKey_braille_dots_68,
    FcitxKey_braille_dots_168,
    FcitxKey_braille_dots_268,
    FcitxKey_braille_dots_1268,
    FcitxKey_braille_dots_368,
    FcitxKey_braille_dots_1368,
    FcitxKey_braille_dots_2368,
    FcitxKey_braille_dots_12368,
    FcitxKey_braille_dots_468,
    FcitxKey_braille_dots_1468,
    FcitxKey_braille_dots_2468,
    FcitxKey_braille_dots_12468,
    FcitxKey_braille_dots_3468,
    FcitxKey_braille_dots_13468,
    FcitxKey_braille_dots_23468,
    FcitxKey_braille_dots_123468,
    FcitxKey_braille_dots_568,
    FcitxKey_braille_dots_1568,
    FcitxKey_braille_dots_2568,
    FcitxKey_braille_dots_12568,
    FcitxKey_braille_dots_3568,
    FcitxKey_braille_dots_13568,
    FcitxKey_braille_dots_23568,
    FcitxKey_braille_dots_123568,
    FcitxKey_braille_dots_4568,
    FcitxKey_braille_dots_14568,
    FcitxKey_braille_dots_24568,
    FcitxKey_braille_dots_124568,
    FcitxKey_braille_dots_34568,
    FcitxKey_braille_dots_134568,
    FcitxKey_braille_dots_234568,
    FcitxKey_braille_dots_1234568,
    FcitxKey_braille_dots_78,
    FcitxKey_braille_dots_178,
    FcitxKey_braille_dots_278,
    FcitxKey_braille_dots_1278,
    FcitxKey_braille_dots_378,
    FcitxKey_braille_dots_1378,
    FcitxKey_braille_dots_2378,
    FcitxKey_braille_dots_12378,
    FcitxKey_braille_dots_478,
    FcitxKey_braille_dots_1478,
    FcitxKey_braille_dots_2478,
    FcitxKey_braille_dots_12478,
    FcitxKey_braille_dots_3478,
    FcitxKey_braille_dots_13478,
    FcitxKey_braille_dots_23478,
    FcitxKey_braille_dots_123478,
    FcitxKey_braille_dots_578,
    FcitxKey_braille_dots_1578,
    FcitxKey_braille_dots_2578,
    FcitxKey_braille_dots_12578,
    FcitxKey_braille_dots_3578,
    FcitxKey_braille_dots_13578,
    FcitxKey_braille_dots_23578,
    FcitxKey_braille_dots_123578,
    FcitxKey_braille_dots_4578,
    FcitxKey_braille_dots_14578,
    FcitxKey_braille_dots_24578,
    FcitxKey_braille_dots_124578,
    FcitxKey_braille_dots_34578,
    FcitxKey_braille_dots_134578,
    FcitxKey_braille_dots_234578,
    FcitxKey_braille_dots_1234578,
    FcitxKey_braille_dots_678,
    FcitxKey_braille_dots_1678,
    FcitxKey_braille_dots_2678,
    FcitxKey_braille_dots_12678,
    FcitxKey_braille_dots_3678,
    FcitxKey_braille_dots_13678,
    FcitxKey_braille_dots_23678,
    FcitxKey_braille_dots_123678,
    FcitxKey_braille_dots_4678,
    FcitxKey_braille_dots_14678,
    FcitxKey_braille_dots_24678,
    FcitxKey_braille_dots_124678,
    FcitxKey_braille_dots_34678,
    FcitxKey_braille_dots_134678,
    FcitxKey_braille_dots_234678,
    FcitxKey_braille_dots_1234678,
    FcitxKey_braille_dots_5678,
    FcitxKey_braille_dots_15678,
    FcitxKey_braille_dots_25678,
    FcitxKey_braille_dots_125678,
    FcitxKey_braille_dots_35678,
    FcitxKey_braille_dots_135678,
    FcitxKey_braille_dots_235678,
    FcitxKey_braille_dots_1235678,
    FcitxKey_braille_dots_45678,
    FcitxKey_braille_dots_145678,
    FcitxKey_braille_dots_245678,
    FcitxKey_braille_dots_1245678,
    FcitxKey_braille_dots_345678,
    FcitxKey_braille_dots_1345678,
    FcitxKey_braille_dots_2345678,
    FcitxKey_braille_dots_12345678,
    FcitxKey_Sinh_ng,
    FcitxKey_Sinh_h2,
    FcitxKey_Sinh_a,
    FcitxKey_Sinh_aa,
    FcitxKey_Sinh_ae,
    FcitxKey_Sinh_aee,
    FcitxKey_Sinh_i,
    FcitxKey_Sinh_ii,
    FcitxKey_Sinh_u,
    FcitxKey_Sinh_uu,
    FcitxKey_Sinh_ri,
    FcitxKey_Sinh_rii,
    FcitxKey_Sinh_lu,
    FcitxKey_Sinh_luu,
    FcitxKey_Sinh_e,
    FcitxKey_Sinh_ee,
    FcitxKey_Sinh_ai,
    FcitxKey_Sinh_o,
    FcitxKey_Sinh_oo,
    FcitxKey_Sinh_au,
    FcitxKey_Sinh_ka,
    FcitxKey_Sinh_kha,
    FcitxKey_Sinh_ga,
    FcitxKey_Sinh_gha,
    FcitxKey_Sinh_ng2,
    FcitxKey_Sinh_nga,
    FcitxKey_Sinh_ca,
    FcitxKey_Sinh_cha,
    FcitxKey_Sinh_ja,
    FcitxKey_Sinh_jha,
    FcitxKey_Sinh_nya,
    FcitxKey_Sinh_jnya,
    FcitxKey_Sinh_nja,
    FcitxKey_Sinh_tta,
    FcitxKey_Sinh_ttha,
    FcitxKey_Sinh_dda,
    FcitxKey_Sinh_ddha,
    FcitxKey_Sinh_nna,
    FcitxKey_Sinh_ndda,
    FcitxKey_Sinh_tha,
    FcitxKey_Sinh_thha,
    FcitxKey_Sinh_dha,
    FcitxKey_Sinh_dhha,
    FcitxKey_Sinh_na,
    FcitxKey_Sinh_ndha,
    FcitxKey_Sinh_pa,
    FcitxKey_Sinh_pha,
    FcitxKey_Sinh_ba,
    FcitxKey_Sinh_bha,
    FcitxKey_Sinh_ma,
    FcitxKey_Sinh_mba,
    FcitxKey_Sinh_ya,
    FcitxKey_Sinh_ra,
    FcitxKey_Sinh_la,
    FcitxKey_Sinh_va,
    FcitxKey_Sinh_sha,
    FcitxKey_Sinh_ssha,
    FcitxKey_Sinh_sa,
    FcitxKey_Sinh_ha,
    FcitxKey_Sinh_lla,
    FcitxKey_Sinh_fa,
    FcitxKey_Sinh_al,
    FcitxKey_Sinh_aa2,
    FcitxKey_Sinh_ae2,
    FcitxKey_Sinh_aee2,
    FcitxKey_Sinh_i2,
    FcitxKey_Sinh_ii2,
    FcitxKey_Sinh_u2,
    FcitxKey_Sinh_uu2,
    FcitxKey_Sinh_ru2,
    FcitxKey_Sinh_e2,
    FcitxKey_Sinh_ee2,
    FcitxKey_Sinh_ai2,
    FcitxKey_Sinh_o2,
    FcitxKey_Sinh_oo2,
    FcitxKey_Sinh_au2,
    FcitxKey_Sinh_lu2,
    FcitxKey_Sinh_ruu2,
    FcitxKey_Sinh_luu2,
    FcitxKey_Sinh_kunddaliya,
};

#ifndef FcitxKey_ISO_Left_Tab
#define FcitxKey_ISO_Left_Tab         0xFE20
#endif

#ifndef FcitxKey_dead_hook
#define FcitxKey_dead_hook            0xFE61
#endif

#ifndef FcitxKey_dead_horn
#define FcitxKey_dead_horn            0xFE62
#endif

#ifndef FcitxKey_Codeinput
#define FcitxKey_Codeinput            0xFF37
#endif

#ifndef FcitxKey_Kanji_Bangou
#define FcitxKey_Kanji_Bangou         0xFF37 /* same as codeinput */
#endif

// Fix old X libraries
#ifndef FcitxKey_KP_Home
#define FcitxKey_KP_Home              0xFF95
#endif
#ifndef FcitxKey_KP_Left
#define FcitxKey_KP_Left              0xFF96
#endif
#ifndef FcitxKey_KP_Up
#define FcitxKey_KP_Up                0xFF97
#endif
#ifndef FcitxKey_KP_Right
#define FcitxKey_KP_Right             0xFF98
#endif
#ifndef FcitxKey_KP_Down
#define FcitxKey_KP_Down              0xFF99
#endif
#ifndef FcitxKey_KP_Prior
#define FcitxKey_KP_Prior             0xFF9A
#endif
#ifndef FcitxKey_KP_Next
#define FcitxKey_KP_Next              0xFF9B
#endif
#ifndef FcitxKey_KP_End
#define FcitxKey_KP_End               0xFF9C
#endif
#ifndef FcitxKey_KP_Insert
#define FcitxKey_KP_Insert            0xFF9E
#endif
#ifndef FcitxKey_KP_Delete
#define FcitxKey_KP_Delete            0xFF9F
#endif

// the next lines are taken on 10/2009 from X.org (X11/XF86keysym.h), defining some special
// multimedia keys. They are included here as not every system has them.
#define XF86FcitxKey_MonBrightnessUp     0x1008FF02
#define XF86FcitxKey_MonBrightnessDown   0x1008FF03
#define XF86FcitxKey_KbdLightOnOff       0x1008FF04
#define XF86FcitxKey_KbdBrightnessUp     0x1008FF05
#define XF86FcitxKey_KbdBrightnessDown   0x1008FF06
#define XF86FcitxKey_Standby             0x1008FF10
#define XF86FcitxKey_AudioLowerVolume    0x1008FF11
#define XF86FcitxKey_AudioMute           0x1008FF12
#define XF86FcitxKey_AudioRaiseVolume    0x1008FF13
#define XF86FcitxKey_AudioPlay           0x1008FF14
#define XF86FcitxKey_AudioStop           0x1008FF15
#define XF86FcitxKey_AudioPrev           0x1008FF16
#define XF86FcitxKey_AudioNext           0x1008FF17
#define XF86FcitxKey_HomePage            0x1008FF18
#define XF86FcitxKey_Mail                0x1008FF19
#define XF86FcitxKey_Start               0x1008FF1A
#define XF86FcitxKey_Search              0x1008FF1B
#define XF86FcitxKey_AudioRecord         0x1008FF1C
#define XF86FcitxKey_Calculator          0x1008FF1D
#define XF86FcitxKey_Memo                0x1008FF1E
#define XF86FcitxKey_ToDoList            0x1008FF1F
#define XF86FcitxKey_Calendar            0x1008FF20
#define XF86FcitxKey_PowerDown           0x1008FF21
#define XF86FcitxKey_ContrastAdjust      0x1008FF22
#define XF86FcitxKey_Back                0x1008FF26
#define XF86FcitxKey_Forward             0x1008FF27
#define XF86FcitxKey_Stop                0x1008FF28
#define XF86FcitxKey_Refresh             0x1008FF29
#define XF86FcitxKey_PowerOff            0x1008FF2A
#define XF86FcitxKey_WakeUp              0x1008FF2B
#define XF86FcitxKey_Eject               0x1008FF2C
#define XF86FcitxKey_ScreenSaver         0x1008FF2D
#define XF86FcitxKey_WWW                 0x1008FF2E
#define XF86FcitxKey_Sleep               0x1008FF2F
#define XF86FcitxKey_Favorites           0x1008FF30
#define XF86FcitxKey_AudioPause          0x1008FF31
#define XF86FcitxKey_AudioMedia          0x1008FF32
#define XF86FcitxKey_MyComputer          0x1008FF33
#define XF86FcitxKey_LightBulb           0x1008FF35
#define XF86FcitxKey_Shop                0x1008FF36
#define XF86FcitxKey_History             0x1008FF37
#define XF86FcitxKey_OpenURL             0x1008FF38
#define XF86FcitxKey_AddFavorite         0x1008FF39
#define XF86FcitxKey_HotLinks            0x1008FF3A
#define XF86FcitxKey_BrightnessAdjust    0x1008FF3B
#define XF86FcitxKey_Finance             0x1008FF3C
#define XF86FcitxKey_Community           0x1008FF3D
#define XF86FcitxKey_AudioRewind         0x1008FF3E
#define XF86FcitxKey_BackForward         0x1008FF3F
#define XF86FcitxKey_Launch0             0x1008FF40
#define XF86FcitxKey_Launch1             0x1008FF41
#define XF86FcitxKey_Launch2             0x1008FF42
#define XF86FcitxKey_Launch3             0x1008FF43
#define XF86FcitxKey_Launch4             0x1008FF44
#define XF86FcitxKey_Launch5             0x1008FF45
#define XF86FcitxKey_Launch6             0x1008FF46
#define XF86FcitxKey_Launch7             0x1008FF47
#define XF86FcitxKey_Launch8             0x1008FF48
#define XF86FcitxKey_Launch9             0x1008FF49
#define XF86FcitxKey_LaunchA             0x1008FF4A
#define XF86FcitxKey_LaunchB             0x1008FF4B
#define XF86FcitxKey_LaunchC             0x1008FF4C
#define XF86FcitxKey_LaunchD             0x1008FF4D
#define XF86FcitxKey_LaunchE             0x1008FF4E
#define XF86FcitxKey_LaunchF             0x1008FF4F
#define XF86FcitxKey_ApplicationLeft     0x1008FF50
#define XF86FcitxKey_ApplicationRight    0x1008FF51
#define XF86FcitxKey_Book                0x1008FF52
#define XF86FcitxKey_CD                  0x1008FF53
#define XF86FcitxKey_Calculater          0x1008FF54
#define XF86FcitxKey_Clear               0x1008FF55
#define XF86FcitxKey_ClearGrab           0x1008FE21
#define XF86FcitxKey_Close               0x1008FF56
#define XF86FcitxKey_Copy                0x1008FF57
#define XF86FcitxKey_Cut                 0x1008FF58
#define XF86FcitxKey_Display             0x1008FF59
#define XF86FcitxKey_DOS                 0x1008FF5A
#define XF86FcitxKey_Documents           0x1008FF5B
#define XF86FcitxKey_Excel               0x1008FF5C
#define XF86FcitxKey_Explorer            0x1008FF5D
#define XF86FcitxKey_Game                0x1008FF5E
#define XF86FcitxKey_Go                  0x1008FF5F
#define XF86FcitxKey_iTouch              0x1008FF60
#define XF86FcitxKey_LogOff              0x1008FF61
#define XF86FcitxKey_Market              0x1008FF62
#define XF86FcitxKey_Meeting             0x1008FF63
#define XF86FcitxKey_MenuKB              0x1008FF65
#define XF86FcitxKey_MenuPB              0x1008FF66
#define XF86FcitxKey_MySites             0x1008FF67
#define XF86FcitxKey_News                0x1008FF69
#define XF86FcitxKey_OfficeHome          0x1008FF6A
#define XF86FcitxKey_Option              0x1008FF6C
#define XF86FcitxKey_Paste               0x1008FF6D
#define XF86FcitxKey_Phone               0x1008FF6E
#define XF86FcitxKey_Reply               0x1008FF72
#define XF86FcitxKey_Reload              0x1008FF73
#define XF86FcitxKey_RotateWindows       0x1008FF74
#define XF86FcitxKey_RotationPB          0x1008FF75
#define XF86FcitxKey_RotationKB          0x1008FF76
#define XF86FcitxKey_Save                0x1008FF77
#define XF86FcitxKey_Send                0x1008FF7B
#define XF86FcitxKey_Spell               0x1008FF7C
#define XF86FcitxKey_SplitScreen         0x1008FF7D
#define XF86FcitxKey_Support             0x1008FF7E
#define XF86FcitxKey_TaskPane            0x1008FF7F
#define XF86FcitxKey_Terminal            0x1008FF80
#define XF86FcitxKey_Tools               0x1008FF81
#define XF86FcitxKey_Travel              0x1008FF82
#define XF86FcitxKey_Video               0x1008FF87
#define XF86FcitxKey_Word                0x1008FF89
#define XF86FcitxKey_Xfer                0x1008FF8A
#define XF86FcitxKey_ZoomIn              0x1008FF8B
#define XF86FcitxKey_ZoomOut             0x1008FF8C
#define XF86FcitxKey_Away                0x1008FF8D
#define XF86FcitxKey_Messenger           0x1008FF8E
#define XF86FcitxKey_WebCam              0x1008FF8F
#define XF86FcitxKey_MailForward         0x1008FF90
#define XF86FcitxKey_Pictures            0x1008FF91
#define XF86FcitxKey_Music               0x1008FF92
#define XF86FcitxKey_Battery             0x1008FF93
#define XF86FcitxKey_Bluetooth           0x1008FF94
#define XF86FcitxKey_WLAN                0x1008FF95
#define XF86FcitxKey_UWB                 0x1008FF96
#define XF86FcitxKey_AudioForward        0x1008FF97
#define XF86FcitxKey_AudioRepeat         0x1008FF98
#define XF86FcitxKey_AudioRandomPlay     0x1008FF99
#define XF86FcitxKey_Subtitle            0x1008FF9A
#define XF86FcitxKey_AudioCycleTrack     0x1008FF9B
#define XF86FcitxKey_Time                0x1008FF9F
#define XF86FcitxKey_Select              0x1008FFA0
#define XF86FcitxKey_View                0x1008FFA1
#define XF86FcitxKey_TopMenu             0x1008FFA2
#define XF86FcitxKey_Suspend             0x1008FFA7
#define XF86FcitxKey_Hibernate           0x1008FFA8
#define XF86FcitxKey_TouchpadToggle      0x1008FFA9
#define XF86FcitxKey_TouchpadOn          0x1008FFB0
#define XF86FcitxKey_TouchpadOff         0x1008FFB1


// end of XF86keysyms.h

QT_BEGIN_NAMESPACE

// keyboard mapping table
static const unsigned int KeyTbl[] = {

    // misc keys

    FcitxKey_Escape,                  Qt::Key_Escape,
    FcitxKey_Tab,                     Qt::Key_Tab,
    FcitxKey_ISO_Left_Tab,            Qt::Key_Backtab,
    FcitxKey_BackSpace,               Qt::Key_Backspace,
    FcitxKey_Return,                  Qt::Key_Return,
    FcitxKey_Insert,                  Qt::Key_Insert,
    FcitxKey_Delete,                  Qt::Key_Delete,
    FcitxKey_Clear,                   Qt::Key_Delete,
    FcitxKey_Pause,                   Qt::Key_Pause,
    FcitxKey_Print,                   Qt::Key_Print,
    0x1005FF60,                 Qt::Key_SysReq,         // hardcoded Sun SysReq
    0x1007ff00,                 Qt::Key_SysReq,         // hardcoded X386 SysReq

    // cursor movement

    FcitxKey_Home,                    Qt::Key_Home,
    FcitxKey_End,                     Qt::Key_End,
    FcitxKey_Left,                    Qt::Key_Left,
    FcitxKey_Up,                      Qt::Key_Up,
    FcitxKey_Right,                   Qt::Key_Right,
    FcitxKey_Down,                    Qt::Key_Down,
    FcitxKey_Prior,                   Qt::Key_PageUp,
    FcitxKey_Next,                    Qt::Key_PageDown,

    // modifiers

    FcitxKey_Shift_L,                 Qt::Key_Shift,
    FcitxKey_Shift_R,                 Qt::Key_Shift,
    FcitxKey_Shift_Lock,              Qt::Key_Shift,
    FcitxKey_Control_L,               Qt::Key_Control,
    FcitxKey_Control_R,               Qt::Key_Control,
    FcitxKey_Meta_L,                  Qt::Key_Meta,
    FcitxKey_Meta_R,                  Qt::Key_Meta,
    FcitxKey_Alt_L,                   Qt::Key_Alt,
    FcitxKey_Alt_R,                   Qt::Key_Alt,
    FcitxKey_Caps_Lock,               Qt::Key_CapsLock,
    FcitxKey_Num_Lock,                Qt::Key_NumLock,
    FcitxKey_Scroll_Lock,             Qt::Key_ScrollLock,
    FcitxKey_Super_L,                 Qt::Key_Super_L,
    FcitxKey_Super_R,                 Qt::Key_Super_R,
    FcitxKey_Menu,                    Qt::Key_Menu,
    FcitxKey_Hyper_L,                 Qt::Key_Hyper_L,
    FcitxKey_Hyper_R,                 Qt::Key_Hyper_R,
    FcitxKey_Help,                    Qt::Key_Help,
    0x1000FF74,                 Qt::Key_Backtab,        // hardcoded HP backtab
    0x1005FF10,                 Qt::Key_F11,            // hardcoded Sun F36 (labeled F11)
    0x1005FF11,                 Qt::Key_F12,            // hardcoded Sun F37 (labeled F12)

    // numeric and function keypad keys

    FcitxKey_KP_Space,                Qt::Key_Space,
    FcitxKey_KP_Tab,                  Qt::Key_Tab,
    FcitxKey_KP_Enter,                Qt::Key_Enter,
    //FcitxKey_KP_F1,                 Qt::Key_F1,
    //FcitxKey_KP_F2,                 Qt::Key_F2,
    //FcitxKey_KP_F3,                 Qt::Key_F3,
    //FcitxKey_KP_F4,                 Qt::Key_F4,
    FcitxKey_KP_Home,                 Qt::Key_Home,
    FcitxKey_KP_Left,                 Qt::Key_Left,
    FcitxKey_KP_Up,                   Qt::Key_Up,
    FcitxKey_KP_Right,                Qt::Key_Right,
    FcitxKey_KP_Down,                 Qt::Key_Down,
    FcitxKey_KP_Prior,                Qt::Key_PageUp,
    FcitxKey_KP_Next,                 Qt::Key_PageDown,
    FcitxKey_KP_End,                  Qt::Key_End,
    FcitxKey_KP_Begin,                Qt::Key_Clear,
    FcitxKey_KP_Insert,               Qt::Key_Insert,
    FcitxKey_KP_Delete,               Qt::Key_Delete,
    FcitxKey_KP_Equal,                Qt::Key_Equal,
    FcitxKey_KP_Multiply,             Qt::Key_Asterisk,
    FcitxKey_KP_Add,                  Qt::Key_Plus,
    FcitxKey_KP_Separator,            Qt::Key_Comma,
    FcitxKey_KP_Subtract,             Qt::Key_Minus,
    FcitxKey_KP_Decimal,              Qt::Key_Period,
    FcitxKey_KP_Divide,               Qt::Key_Slash,

    // International input method support keys

    // International & multi-key character composition
    FcitxKey_ISO_Level3_Shift,        Qt::Key_AltGr,
    FcitxKey_Multi_key,       Qt::Key_Multi_key,
    FcitxKey_Codeinput,       Qt::Key_Codeinput,
    FcitxKey_SingleCandidate,     Qt::Key_SingleCandidate,
    FcitxKey_MultipleCandidate,   Qt::Key_MultipleCandidate,
    FcitxKey_PreviousCandidate,   Qt::Key_PreviousCandidate,

    // Misc Functions
    FcitxKey_Mode_switch,     Qt::Key_Mode_switch,
    FcitxKey_script_switch,       Qt::Key_Mode_switch,

    // Japanese keyboard support
    FcitxKey_Kanji,           Qt::Key_Kanji,
    FcitxKey_Muhenkan,        Qt::Key_Muhenkan,
    //FcitxKey_Henkan_Mode,       Qt::Key_Henkan_Mode,
    FcitxKey_Henkan_Mode,     Qt::Key_Henkan,
    FcitxKey_Henkan,          Qt::Key_Henkan,
    FcitxKey_Romaji,          Qt::Key_Romaji,
    FcitxKey_Hiragana,        Qt::Key_Hiragana,
    FcitxKey_Katakana,        Qt::Key_Katakana,
    FcitxKey_Hiragana_Katakana,   Qt::Key_Hiragana_Katakana,
    FcitxKey_Zenkaku,         Qt::Key_Zenkaku,
    FcitxKey_Hankaku,         Qt::Key_Hankaku,
    FcitxKey_Zenkaku_Hankaku,     Qt::Key_Zenkaku_Hankaku,
    FcitxKey_Touroku,         Qt::Key_Touroku,
    FcitxKey_Massyo,          Qt::Key_Massyo,
    FcitxKey_Kana_Lock,       Qt::Key_Kana_Lock,
    FcitxKey_Kana_Shift,      Qt::Key_Kana_Shift,
    FcitxKey_Eisu_Shift,      Qt::Key_Eisu_Shift,
    FcitxKey_Eisu_toggle,     Qt::Key_Eisu_toggle,
    //FcitxKey_Kanji_Bangou,      Qt::Key_Kanji_Bangou,
    //FcitxKey_Zen_Koho,      Qt::Key_Zen_Koho,
    //FcitxKey_Mae_Koho,      Qt::Key_Mae_Koho,
    FcitxKey_Kanji_Bangou,        Qt::Key_Codeinput,
    FcitxKey_Zen_Koho,        Qt::Key_MultipleCandidate,
    FcitxKey_Mae_Koho,        Qt::Key_PreviousCandidate,

#ifdef FcitxKey_KOREAN
    // Korean keyboard support
    FcitxKey_Hangul,          Qt::Key_Hangul,
    FcitxKey_Hangul_Start,        Qt::Key_Hangul_Start,
    FcitxKey_Hangul_End,      Qt::Key_Hangul_End,
    FcitxKey_Hangul_Hanja,        Qt::Key_Hangul_Hanja,
    FcitxKey_Hangul_Jamo,     Qt::Key_Hangul_Jamo,
    FcitxKey_Hangul_Romaja,       Qt::Key_Hangul_Romaja,
    //FcitxKey_Hangul_Codeinput,  Qt::Key_Hangul_Codeinput,
    FcitxKey_Hangul_Codeinput,    Qt::Key_Codeinput,
    FcitxKey_Hangul_Jeonja,       Qt::Key_Hangul_Jeonja,
    FcitxKey_Hangul_Banja,        Qt::Key_Hangul_Banja,
    FcitxKey_Hangul_PreHanja,     Qt::Key_Hangul_PreHanja,
    FcitxKey_Hangul_PostHanja,    Qt::Key_Hangul_PostHanja,
    //FcitxKey_Hangul_SingleCandidate,Qt::Key_Hangul_SingleCandidate,
    //FcitxKey_Hangul_MultipleCandidate,Qt::Key_Hangul_MultipleCandidate,
    //FcitxKey_Hangul_PreviousCandidate,Qt::Key_Hangul_PreviousCandidate,
    FcitxKey_Hangul_SingleCandidate,  Qt::Key_SingleCandidate,
    FcitxKey_Hangul_MultipleCandidate,Qt::Key_MultipleCandidate,
    FcitxKey_Hangul_PreviousCandidate,Qt::Key_PreviousCandidate,
    FcitxKey_Hangul_Special,      Qt::Key_Hangul_Special,
    //FcitxKey_Hangul_switch,     Qt::Key_Hangul_switch,
    FcitxKey_Hangul_switch,       Qt::Key_Mode_switch,
#endif  // FcitxKey_KOREAN

    // dead keys
    FcitxKey_dead_grave,              Qt::Key_Dead_Grave,
    FcitxKey_dead_acute,              Qt::Key_Dead_Acute,
    FcitxKey_dead_circumflex,         Qt::Key_Dead_Circumflex,
    FcitxKey_dead_tilde,              Qt::Key_Dead_Tilde,
    FcitxKey_dead_macron,             Qt::Key_Dead_Macron,
    FcitxKey_dead_breve,              Qt::Key_Dead_Breve,
    FcitxKey_dead_abovedot,           Qt::Key_Dead_Abovedot,
    FcitxKey_dead_diaeresis,          Qt::Key_Dead_Diaeresis,
    FcitxKey_dead_abovering,          Qt::Key_Dead_Abovering,
    FcitxKey_dead_doubleacute,        Qt::Key_Dead_Doubleacute,
    FcitxKey_dead_caron,              Qt::Key_Dead_Caron,
    FcitxKey_dead_cedilla,            Qt::Key_Dead_Cedilla,
    FcitxKey_dead_ogonek,             Qt::Key_Dead_Ogonek,
    FcitxKey_dead_iota,               Qt::Key_Dead_Iota,
    FcitxKey_dead_voiced_sound,       Qt::Key_Dead_Voiced_Sound,
    FcitxKey_dead_semivoiced_sound,   Qt::Key_Dead_Semivoiced_Sound,
    FcitxKey_dead_belowdot,           Qt::Key_Dead_Belowdot,
    FcitxKey_dead_hook,               Qt::Key_Dead_Hook,
    FcitxKey_dead_horn,               Qt::Key_Dead_Horn,

    // Special keys from X.org - This include multimedia keys,
    // wireless/bluetooth/uwb keys, special launcher keys, etc.
    XF86FcitxKey_Back,                Qt::Key_Back,
    XF86FcitxKey_Forward,             Qt::Key_Forward,
    XF86FcitxKey_Stop,                Qt::Key_Stop,
    XF86FcitxKey_Refresh,             Qt::Key_Refresh,
    XF86FcitxKey_Favorites,           Qt::Key_Favorites,
    XF86FcitxKey_AudioMedia,          Qt::Key_LaunchMedia,
    XF86FcitxKey_OpenURL,             Qt::Key_OpenUrl,
    XF86FcitxKey_HomePage,            Qt::Key_HomePage,
    XF86FcitxKey_Search,              Qt::Key_Search,
    XF86FcitxKey_AudioLowerVolume,    Qt::Key_VolumeDown,
    XF86FcitxKey_AudioMute,           Qt::Key_VolumeMute,
    XF86FcitxKey_AudioRaiseVolume,    Qt::Key_VolumeUp,
    XF86FcitxKey_AudioPlay,           Qt::Key_MediaPlay,
    XF86FcitxKey_AudioStop,           Qt::Key_MediaStop,
    XF86FcitxKey_AudioPrev,           Qt::Key_MediaPrevious,
    XF86FcitxKey_AudioNext,           Qt::Key_MediaNext,
    XF86FcitxKey_AudioRecord,         Qt::Key_MediaRecord,
    XF86FcitxKey_Mail,                Qt::Key_LaunchMail,
    XF86FcitxKey_MyComputer,          Qt::Key_Launch0,  // ### Qt 6: remap properly
    XF86FcitxKey_Calculator,          Qt::Key_Launch1,
    XF86FcitxKey_Memo,                Qt::Key_Memo,
    XF86FcitxKey_ToDoList,            Qt::Key_ToDoList,
    XF86FcitxKey_Calendar,            Qt::Key_Calendar,
    XF86FcitxKey_PowerDown,           Qt::Key_PowerDown,
    XF86FcitxKey_ContrastAdjust,      Qt::Key_ContrastAdjust,
    XF86FcitxKey_Standby,             Qt::Key_Standby,
    XF86FcitxKey_MonBrightnessUp,     Qt::Key_MonBrightnessUp,
    XF86FcitxKey_MonBrightnessDown,   Qt::Key_MonBrightnessDown,
    XF86FcitxKey_KbdLightOnOff,       Qt::Key_KeyboardLightOnOff,
    XF86FcitxKey_KbdBrightnessUp,     Qt::Key_KeyboardBrightnessUp,
    XF86FcitxKey_KbdBrightnessDown,   Qt::Key_KeyboardBrightnessDown,
    XF86FcitxKey_PowerOff,            Qt::Key_PowerOff,
    XF86FcitxKey_WakeUp,              Qt::Key_WakeUp,
    XF86FcitxKey_Eject,               Qt::Key_Eject,
    XF86FcitxKey_ScreenSaver,         Qt::Key_ScreenSaver,
    XF86FcitxKey_WWW,                 Qt::Key_WWW,
    XF86FcitxKey_Sleep,               Qt::Key_Sleep,
    XF86FcitxKey_LightBulb,           Qt::Key_LightBulb,
    XF86FcitxKey_Shop,                Qt::Key_Shop,
    XF86FcitxKey_History,             Qt::Key_History,
    XF86FcitxKey_AddFavorite,         Qt::Key_AddFavorite,
    XF86FcitxKey_HotLinks,            Qt::Key_HotLinks,
    XF86FcitxKey_BrightnessAdjust,    Qt::Key_BrightnessAdjust,
    XF86FcitxKey_Finance,             Qt::Key_Finance,
    XF86FcitxKey_Community,           Qt::Key_Community,
    XF86FcitxKey_AudioRewind,         Qt::Key_AudioRewind,
    XF86FcitxKey_BackForward,         Qt::Key_BackForward,
    XF86FcitxKey_ApplicationLeft,     Qt::Key_ApplicationLeft,
    XF86FcitxKey_ApplicationRight,    Qt::Key_ApplicationRight,
    XF86FcitxKey_Book,                Qt::Key_Book,
    XF86FcitxKey_CD,                  Qt::Key_CD,
    XF86FcitxKey_Calculater,          Qt::Key_Calculator,
    XF86FcitxKey_Clear,               Qt::Key_Clear,
    XF86FcitxKey_ClearGrab,           Qt::Key_ClearGrab,
    XF86FcitxKey_Close,               Qt::Key_Close,
    XF86FcitxKey_Copy,                Qt::Key_Copy,
    XF86FcitxKey_Cut,                 Qt::Key_Cut,
    XF86FcitxKey_Display,             Qt::Key_Display,
    XF86FcitxKey_DOS,                 Qt::Key_DOS,
    XF86FcitxKey_Documents,           Qt::Key_Documents,
    XF86FcitxKey_Excel,               Qt::Key_Excel,
    XF86FcitxKey_Explorer,            Qt::Key_Explorer,
    XF86FcitxKey_Game,                Qt::Key_Game,
    XF86FcitxKey_Go,                  Qt::Key_Go,
    XF86FcitxKey_iTouch,              Qt::Key_iTouch,
    XF86FcitxKey_LogOff,              Qt::Key_LogOff,
    XF86FcitxKey_Market,              Qt::Key_Market,
    XF86FcitxKey_Meeting,             Qt::Key_Meeting,
    XF86FcitxKey_MenuKB,              Qt::Key_MenuKB,
    XF86FcitxKey_MenuPB,              Qt::Key_MenuPB,
    XF86FcitxKey_MySites,             Qt::Key_MySites,
    XF86FcitxKey_News,                Qt::Key_News,
    XF86FcitxKey_OfficeHome,          Qt::Key_OfficeHome,
    XF86FcitxKey_Option,              Qt::Key_Option,
    XF86FcitxKey_Paste,               Qt::Key_Paste,
    XF86FcitxKey_Phone,               Qt::Key_Phone,
    XF86FcitxKey_Reply,               Qt::Key_Reply,
    XF86FcitxKey_Reload,              Qt::Key_Reload,
    XF86FcitxKey_RotateWindows,       Qt::Key_RotateWindows,
    XF86FcitxKey_RotationPB,          Qt::Key_RotationPB,
    XF86FcitxKey_RotationKB,          Qt::Key_RotationKB,
    XF86FcitxKey_Save,                Qt::Key_Save,
    XF86FcitxKey_Send,                Qt::Key_Send,
    XF86FcitxKey_Spell,               Qt::Key_Spell,
    XF86FcitxKey_SplitScreen,         Qt::Key_SplitScreen,
    XF86FcitxKey_Support,             Qt::Key_Support,
    XF86FcitxKey_TaskPane,            Qt::Key_TaskPane,
    XF86FcitxKey_Terminal,            Qt::Key_Terminal,
    XF86FcitxKey_Tools,               Qt::Key_Tools,
    XF86FcitxKey_Travel,              Qt::Key_Travel,
    XF86FcitxKey_Video,               Qt::Key_Video,
    XF86FcitxKey_Word,                Qt::Key_Word,
    XF86FcitxKey_Xfer,                Qt::Key_Xfer,
    XF86FcitxKey_ZoomIn,              Qt::Key_ZoomIn,
    XF86FcitxKey_ZoomOut,             Qt::Key_ZoomOut,
    XF86FcitxKey_Away,                Qt::Key_Away,
    XF86FcitxKey_Messenger,           Qt::Key_Messenger,
    XF86FcitxKey_WebCam,              Qt::Key_WebCam,
    XF86FcitxKey_MailForward,         Qt::Key_MailForward,
    XF86FcitxKey_Pictures,            Qt::Key_Pictures,
    XF86FcitxKey_Music,               Qt::Key_Music,
    XF86FcitxKey_Battery,             Qt::Key_Battery,
    XF86FcitxKey_Bluetooth,           Qt::Key_Bluetooth,
    XF86FcitxKey_WLAN,                Qt::Key_WLAN,
    XF86FcitxKey_UWB,                 Qt::Key_UWB,
    XF86FcitxKey_AudioForward,        Qt::Key_AudioForward,
    XF86FcitxKey_AudioRepeat,         Qt::Key_AudioRepeat,
    XF86FcitxKey_AudioRandomPlay,     Qt::Key_AudioRandomPlay,
    XF86FcitxKey_Subtitle,            Qt::Key_Subtitle,
    XF86FcitxKey_AudioCycleTrack,     Qt::Key_AudioCycleTrack,
    XF86FcitxKey_Time,                Qt::Key_Time,
    XF86FcitxKey_Select,              Qt::Key_Select,
    XF86FcitxKey_View,                Qt::Key_View,
    XF86FcitxKey_TopMenu,             Qt::Key_TopMenu,
    XF86FcitxKey_Bluetooth,           Qt::Key_Bluetooth,
    XF86FcitxKey_Suspend,             Qt::Key_Suspend,
    XF86FcitxKey_Hibernate,           Qt::Key_Hibernate,
    XF86FcitxKey_Launch0,             Qt::Key_Launch2, // ### Qt 6: remap properly
    XF86FcitxKey_Launch1,             Qt::Key_Launch3,
    XF86FcitxKey_Launch2,             Qt::Key_Launch4,
    XF86FcitxKey_Launch3,             Qt::Key_Launch5,
    XF86FcitxKey_Launch4,             Qt::Key_Launch6,
    XF86FcitxKey_Launch5,             Qt::Key_Launch7,
    XF86FcitxKey_Launch6,             Qt::Key_Launch8,
    XF86FcitxKey_Launch7,             Qt::Key_Launch9,
    XF86FcitxKey_Launch8,             Qt::Key_LaunchA,
    XF86FcitxKey_Launch9,             Qt::Key_LaunchB,
    XF86FcitxKey_LaunchA,             Qt::Key_LaunchC,
    XF86FcitxKey_LaunchB,             Qt::Key_LaunchD,
    XF86FcitxKey_LaunchC,             Qt::Key_LaunchE,
    XF86FcitxKey_LaunchD,             Qt::Key_LaunchF,
    XF86FcitxKey_LaunchE,             Qt::Key_LaunchG,
    XF86FcitxKey_LaunchF,             Qt::Key_LaunchH,

    0,                          0
};

static const unsigned short katakanaKeysymsToUnicode[] = {
    0x0000, 0x3002, 0x300C, 0x300D, 0x3001, 0x30FB, 0x30F2, 0x30A1,
    0x30A3, 0x30A5, 0x30A7, 0x30A9, 0x30E3, 0x30E5, 0x30E7, 0x30C3,
    0x30FC, 0x30A2, 0x30A4, 0x30A6, 0x30A8, 0x30AA, 0x30AB, 0x30AD,
    0x30AF, 0x30B1, 0x30B3, 0x30B5, 0x30B7, 0x30B9, 0x30BB, 0x30BD,
    0x30BF, 0x30C1, 0x30C4, 0x30C6, 0x30C8, 0x30CA, 0x30CB, 0x30CC,
    0x30CD, 0x30CE, 0x30CF, 0x30D2, 0x30D5, 0x30D8, 0x30DB, 0x30DE,
    0x30DF, 0x30E0, 0x30E1, 0x30E2, 0x30E4, 0x30E6, 0x30E8, 0x30E9,
    0x30EA, 0x30EB, 0x30EC, 0x30ED, 0x30EF, 0x30F3, 0x309B, 0x309C
};

static const unsigned short cyrillicKeysymsToUnicode[] = {
    0x0000, 0x0452, 0x0453, 0x0451, 0x0454, 0x0455, 0x0456, 0x0457,
    0x0458, 0x0459, 0x045a, 0x045b, 0x045c, 0x0000, 0x045e, 0x045f,
    0x2116, 0x0402, 0x0403, 0x0401, 0x0404, 0x0405, 0x0406, 0x0407,
    0x0408, 0x0409, 0x040a, 0x040b, 0x040c, 0x0000, 0x040e, 0x040f,
    0x044e, 0x0430, 0x0431, 0x0446, 0x0434, 0x0435, 0x0444, 0x0433,
    0x0445, 0x0438, 0x0439, 0x043a, 0x043b, 0x043c, 0x043d, 0x043e,
    0x043f, 0x044f, 0x0440, 0x0441, 0x0442, 0x0443, 0x0436, 0x0432,
    0x044c, 0x044b, 0x0437, 0x0448, 0x044d, 0x0449, 0x0447, 0x044a,
    0x042e, 0x0410, 0x0411, 0x0426, 0x0414, 0x0415, 0x0424, 0x0413,
    0x0425, 0x0418, 0x0419, 0x041a, 0x041b, 0x041c, 0x041d, 0x041e,
    0x041f, 0x042f, 0x0420, 0x0421, 0x0422, 0x0423, 0x0416, 0x0412,
    0x042c, 0x042b, 0x0417, 0x0428, 0x042d, 0x0429, 0x0427, 0x042a
};

static const unsigned short greekKeysymsToUnicode[] = {
    0x0000, 0x0386, 0x0388, 0x0389, 0x038a, 0x03aa, 0x0000, 0x038c,
    0x038e, 0x03ab, 0x0000, 0x038f, 0x0000, 0x0000, 0x0385, 0x2015,
    0x0000, 0x03ac, 0x03ad, 0x03ae, 0x03af, 0x03ca, 0x0390, 0x03cc,
    0x03cd, 0x03cb, 0x03b0, 0x03ce, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0391, 0x0392, 0x0393, 0x0394, 0x0395, 0x0396, 0x0397,
    0x0398, 0x0399, 0x039a, 0x039b, 0x039c, 0x039d, 0x039e, 0x039f,
    0x03a0, 0x03a1, 0x03a3, 0x0000, 0x03a4, 0x03a5, 0x03a6, 0x03a7,
    0x03a8, 0x03a9, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x03b1, 0x03b2, 0x03b3, 0x03b4, 0x03b5, 0x03b6, 0x03b7,
    0x03b8, 0x03b9, 0x03ba, 0x03bb, 0x03bc, 0x03bd, 0x03be, 0x03bf,
    0x03c0, 0x03c1, 0x03c3, 0x03c2, 0x03c4, 0x03c5, 0x03c6, 0x03c7,
    0x03c8, 0x03c9, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
};

static const unsigned short technicalKeysymsToUnicode[] = {
    0x0000, 0x23B7, 0x250C, 0x2500, 0x2320, 0x2321, 0x2502, 0x23A1,
    0x23A3, 0x23A4, 0x23A6, 0x239B, 0x239D, 0x239E, 0x23A0, 0x23A8,
    0x23AC, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x2264, 0x2260, 0x2265, 0x222B,
    0x2234, 0x221D, 0x221E, 0x0000, 0x0000, 0x2207, 0x0000, 0x0000,
    0x223C, 0x2243, 0x0000, 0x0000, 0x0000, 0x21D4, 0x21D2, 0x2261,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x221A, 0x0000,
    0x0000, 0x0000, 0x2282, 0x2283, 0x2229, 0x222A, 0x2227, 0x2228,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x2202,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0192, 0x0000,
    0x0000, 0x0000, 0x0000, 0x2190, 0x2191, 0x2192, 0x2193, 0x0000
};

static const unsigned short specialKeysymsToUnicode[] = {
    0x25C6, 0x2592, 0x2409, 0x240C, 0x240D, 0x240A, 0x0000, 0x0000,
    0x2424, 0x240B, 0x2518, 0x2510, 0x250C, 0x2514, 0x253C, 0x23BA,
    0x23BB, 0x2500, 0x23BC, 0x23BD, 0x251C, 0x2524, 0x2534, 0x252C,
    0x2502, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000
};

static const unsigned short publishingKeysymsToUnicode[] = {
    0x0000, 0x2003, 0x2002, 0x2004, 0x2005, 0x2007, 0x2008, 0x2009,
    0x200a, 0x2014, 0x2013, 0x0000, 0x0000, 0x0000, 0x2026, 0x2025,
    0x2153, 0x2154, 0x2155, 0x2156, 0x2157, 0x2158, 0x2159, 0x215a,
    0x2105, 0x0000, 0x0000, 0x2012, 0x2329, 0x0000, 0x232a, 0x0000,
    0x0000, 0x0000, 0x0000, 0x215b, 0x215c, 0x215d, 0x215e, 0x0000,
    0x0000, 0x2122, 0x2613, 0x0000, 0x25c1, 0x25b7, 0x25cb, 0x25af,
    0x2018, 0x2019, 0x201c, 0x201d, 0x211e, 0x0000, 0x2032, 0x2033,
    0x0000, 0x271d, 0x0000, 0x25ac, 0x25c0, 0x25b6, 0x25cf, 0x25ae,
    0x25e6, 0x25ab, 0x25ad, 0x25b3, 0x25bd, 0x2606, 0x2022, 0x25aa,
    0x25b2, 0x25bc, 0x261c, 0x261e, 0x2663, 0x2666, 0x2665, 0x0000,
    0x2720, 0x2020, 0x2021, 0x2713, 0x2717, 0x266f, 0x266d, 0x2642,
    0x2640, 0x260e, 0x2315, 0x2117, 0x2038, 0x201a, 0x201e, 0x0000
};

static const unsigned short aplKeysymsToUnicode[] = {
    0x0000, 0x0000, 0x0000, 0x003c, 0x0000, 0x0000, 0x003e, 0x0000,
    0x2228, 0x2227, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x00af, 0x0000, 0x22a5, 0x2229, 0x230a, 0x0000, 0x005f, 0x0000,
    0x0000, 0x0000, 0x2218, 0x0000, 0x2395, 0x0000, 0x22a4, 0x25cb,
    0x0000, 0x0000, 0x0000, 0x2308, 0x0000, 0x0000, 0x222a, 0x0000,
    0x2283, 0x0000, 0x2282, 0x0000, 0x22a2, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x22a3, 0x0000, 0x0000, 0x0000
};

static const unsigned short koreanKeysymsToUnicode[] = {
    0x0000, 0x3131, 0x3132, 0x3133, 0x3134, 0x3135, 0x3136, 0x3137,
    0x3138, 0x3139, 0x313a, 0x313b, 0x313c, 0x313d, 0x313e, 0x313f,
    0x3140, 0x3141, 0x3142, 0x3143, 0x3144, 0x3145, 0x3146, 0x3147,
    0x3148, 0x3149, 0x314a, 0x314b, 0x314c, 0x314d, 0x314e, 0x314f,
    0x3150, 0x3151, 0x3152, 0x3153, 0x3154, 0x3155, 0x3156, 0x3157,
    0x3158, 0x3159, 0x315a, 0x315b, 0x315c, 0x315d, 0x315e, 0x315f,
    0x3160, 0x3161, 0x3162, 0x3163, 0x11a8, 0x11a9, 0x11aa, 0x11ab,
    0x11ac, 0x11ad, 0x11ae, 0x11af, 0x11b0, 0x11b1, 0x11b2, 0x11b3,
    0x11b4, 0x11b5, 0x11b6, 0x11b7, 0x11b8, 0x11b9, 0x11ba, 0x11bb,
    0x11bc, 0x11bd, 0x11be, 0x11bf, 0x11c0, 0x11c1, 0x11c2, 0x316d,
    0x3171, 0x3178, 0x317f, 0x3181, 0x3184, 0x3186, 0x318d, 0x318e,
    0x11eb, 0x11f0, 0x11f9, 0x0000, 0x0000, 0x0000, 0x0000, 0x20a9
};

static QChar keysymToUnicode(unsigned char byte3, unsigned char byte4)
{
    switch (byte3) {
    case 0x04:
        // katakana
        if (byte4 > 0xa0 && byte4 < 0xe0)
            return QChar(katakanaKeysymsToUnicode[byte4 - 0xa0]);
        else if (byte4 == 0x7e)
            return QChar(0x203e); // Overline
        break;
    case 0x06:
        // russian, use lookup table
        if (byte4 > 0xa0)
            return QChar(cyrillicKeysymsToUnicode[byte4 - 0xa0]);
        break;
    case 0x07:
        // greek
        if (byte4 > 0xa0)
            return QChar(greekKeysymsToUnicode[byte4 - 0xa0]);
        break;
    case 0x08:
        // technical
        if (byte4 > 0xa0)
            return QChar(technicalKeysymsToUnicode[byte4 - 0xa0]);
        break;
    case 0x09:
        // special
        if (byte4 >= 0xe0)
            return QChar(specialKeysymsToUnicode[byte4 - 0xe0]);
        break;
    case 0x0a:
        // publishing
        if (byte4 > 0xa0)
            return QChar(publishingKeysymsToUnicode[byte4 - 0xa0]);
        break;
    case 0x0b:
        // APL
        if (byte4 > 0xa0)
            return QChar(aplKeysymsToUnicode[byte4 - 0xa0]);
        break;
    case 0x0e:
        // Korean
        if (byte4 > 0xa0)
            return QChar(koreanKeysymsToUnicode[byte4 - 0xa0]);
        break;
    default:
        break;
    }
    return QChar(0x0);
}

int translateKeySym(uint key)
{
    int code = -1;
    int i = 0;                                // any other keys
    while (KeyTbl[i]) {
        if (key == KeyTbl[i]) {
            code = (int)KeyTbl[i+1];
            break;
        }
        i += 2;
    }
    return code;
}

QString translateKeySym(int keysym, uint xmodifiers,
                        int &code, Qt::KeyboardModifiers &modifiers,
                        QByteArray &chars, int &count)
{
    // all keysyms smaller than 0xff00 are actally keys that can be mapped to unicode chars

    QTextCodec *mapper = QTextCodec::codecForLocale();
    QChar converted;

    if (/*count == 0 &&*/ keysym < 0xff00) {
        unsigned char byte3 = (unsigned char)(keysym >> 8);
        int mib = -1;
        switch(byte3) {
        case 0: // Latin 1
        case 1: // Latin 2
        case 2: //latin 3
        case 3: // latin4
            mib = byte3 + 4;
            break;
        case 5: // arabic
            mib = 82;
            break;
        case 12: // Hebrew
            mib = 85;
            break;
        case 13: // Thai
            mib = 2259;
            break;
        case 4: // kana
        case 6: // cyrillic
        case 7: // greek
        case 8: // technical, no mapping here at the moment
        case 9: // Special
        case 10: // Publishing
        case 11: // APL
        case 14: // Korean, no mapping
            mib = -1; // manual conversion
            mapper= 0;
            converted = keysymToUnicode(byte3, keysym & 0xff);
            break;
        case 0x20:
            // currency symbols
            if (keysym >= 0x20a0 && keysym <= 0x20ac) {
                mib = -1; // manual conversion
                mapper = 0;
                converted = (uint)keysym;
            }
            break;
        default:
            break;
        }
        if (mib != -1) {
            mapper = QTextCodec::codecForMib(mib);
            if (chars.isEmpty())
                chars.resize(1);
            chars[0] = (unsigned char) (keysym & 0xff); // get only the fourth bit for conversion later
            count = 1;
        }
    } else if (keysym >= 0x1000000 && keysym <= 0x100ffff) {
        converted = (ushort) (keysym - 0x1000000);
        mapper = 0;
    }
    if (count < (int)chars.size()-1)
        chars[count] = '\0';

    QString text;
    if (!mapper && converted.unicode() != 0x0) {
        text = converted;
    } else if (!chars.isEmpty()) {
        // convert chars (8bit) to text (unicode).
        if (mapper)
            text = mapper->toUnicode(chars.data(), count, 0);
        if (text.isEmpty()) {
            // no mapper, or codec couldn't convert to unicode (this
            // can happen when running in the C locale or with no LANG
            // set). try converting from latin-1
            text = QString::fromLatin1(chars);
        }
    }

    if (xmodifiers & FcitxKeyState_Alt) {
        modifiers |= Qt::AltModifier;
    }

    if (xmodifiers & FcitxKeyState_Shift) {
        modifiers |= Qt::ShiftModifier;
    }

    if (xmodifiers & FcitxKeyState_Ctrl) {
        modifiers |= Qt::ControlModifier;
    }

    if (xmodifiers & FcitxKeyState_Super) {
        modifiers |= Qt::MetaModifier;
    }

    // Commentary in X11/keysymdef says that X codes match ASCII, so it
    // is safe to use the locale functions to process X codes in ISO8859-1.
    //
    // This is mainly for compatibility - applications should not use the
    // Qt keycodes between 128 and 255, but should rather use the
    // QKeyEvent::text().
    //
    if (keysym < 128 || (keysym < 256 && (!mapper || mapper->mibEnum()==4))) {
        // upper-case key, if known
        code = isprint((int)keysym) ? toupper((int)keysym) : 0;
    } else if (keysym >= FcitxKey_F1 && keysym <= FcitxKey_F35) {
        // function keys
        code = Qt::Key_F1 + ((int)keysym - FcitxKey_F1);
    } else if (keysym >= FcitxKey_KP_Space && keysym <= FcitxKey_KP_9) {
        if (keysym >= FcitxKey_KP_0) {
            // numeric keypad keys
            code = Qt::Key_0 + ((int)keysym - FcitxKey_KP_0);
        } else {
            code = translateKeySym(keysym);
        }
        modifiers |= Qt::KeypadModifier;
    } else if (text.length() == 1 && text.unicode()->unicode() > 0x1f && text.unicode()->unicode() != 0x7f && !(keysym >= FcitxKey_dead_grave && keysym <= FcitxKey_dead_horn)) {
        code = text.unicode()->toUpper().unicode();
    } else {
        // any other keys
        code = translateKeySym(keysym);

        if (code == Qt::Key_Tab && (modifiers & Qt::ShiftModifier)) {
            // map shift+tab to shift+backtab, QShortcutMap knows about it
            // and will handle it.
            code = Qt::Key_Backtab;
            text = QString();
        }
    }

    return text;
}

bool symToKeyQt(int sym, unsigned int state, int& qtcode, Qt::KeyboardModifiers& mod)
{
    QByteArray chars;
    int count = 0;

    translateKeySym(sym, state, qtcode, mod, chars, count);

    return qtcode >= 0;
}

bool keyQtToSym(int qtcode, Qt::KeyboardModifiers mod, int& sym, unsigned int& state)
{
    qEventToSym(qtcode, QString(), mod, sym, state);

    return sym >= 0;
}
